import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import {buildOperatingReview,checkMetricClaim,validDate} from './operating-review.mjs';import {progressMethods} from './progress-store.mjs';
const fixture=JSON.parse(readFileSync(new URL('../../examples/operating-review/case.json',import.meta.url)));
function revised(){const d=structuredClone(fixture);d.sources[0].status='superseded';d.sources[1].status='accepted';d.sourceVersion=2;return d;}
test('monthly independent arithmetic, negative cash headroom and no annualized leverage',()=>{const r=buildOperatingReview(revised());assert.equal(r.lines[0].delta,-200000);assert.equal(r.lines[1].delta,-160000);assert.equal(r.derived[0].actual,2950000);assert.equal(r.derived[0].delta,850000);assert.equal(r.derived[1].actual,-150000);assert.equal(r.derived[2].actual,10);assert.ok(r.concerns.some(c=>c.key==='cash-minimum'));});
test('point-in-time restores prior source when the replacement was unavailable',()=>{const d=revised();d.operatingReview.cutoff='2026-08-07';const r=buildOperatingReview(d);assert.equal(r.lines[0].actual.value,1000000);assert.deepEqual(r.admittedSources,['monthly-original']);assert.ok(r.exclusions.some(e=>e.sourceId==='monthly-revised'));});
test('wrong valid citation, wrong period, scenario and value cannot pass numeric support',()=>{const d=revised(),claim={metric:'revenue',basis:'actual',period:'2026-07',currency:'USD',scenario:'Base',ref:'monthly-revised:1',value:900000};assert.equal(checkMetricClaim(d,claim).grade,'supported');assert.equal(checkMetricClaim(d,{...claim,ref:'monthly-revised:2'}).grade,'unsupported');assert.equal(checkMetricClaim(d,{...claim,period:'2026-06'}).grade,'unsupported');assert.equal(checkMetricClaim(d,{...claim,scenario:'Downside'}).grade,'unsupported');assert.equal(checkMetricClaim(d,{...claim,value:1000000}).grade,'contradicted');});
test('conflicts, duration, currency and definition changes are explicit',()=>{const d=revised();d.sources[1].mapping.rows.push({...d.sources[1].mapping.rows[0],ref:'other'});assert.equal(buildOperatingReview(d).lines[0].status,'conflicting');assert.equal(buildOperatingReview(d).derived[2].actual,null);d.sources[1].mapping.rows.pop();d.sources[1].mapping.rows[0].periodType='year';assert.equal(buildOperatingReview(d).lines[0].actual,null);d.sources[1].mapping.rows[0].periodType='month';d.sources[1].mapping.rows[0].definition='ARR';assert.equal(buildOperatingReview(d).lines[0].delta,null);d.sources[1].mapping.currency='EUR';assert.equal(buildOperatingReview(d).lines[0].actual,null);});
test('cutoff metadata is immutable after approval; output invalidation and MCP cutoff enforced',()=>{const db=new DatabaseSync(':memory:'),api=progressMethods(db);try{api.progressSave({state:fixture,baseVersion:null});const next=structuredClone(fixture);next.outputs['Partner update']={text:'initial',sourceVersion:1,stale:false};api.progressSave({state:next,baseVersion:1});next.operatingReview.cutoff='2026-08-04';const saved=api.progressSave({state:next,baseVersion:2});assert.equal(saved.state.outputs['Partner update'].stale,true);assert.throws(()=>api.progressRelease(next.id,['monthly-original']),/cutoff/);next.sources[0].availableOn='2026-08-01';assert.throws(()=>api.progressSave({state:next,baseVersion:3}),/new source version/);}finally{db.close();}});
test('invalid dates fail without normalization or an exception',()=>{for(const d of ['2026-13-01','2026-02-30','garbage'])assert.equal(validDate(d),false);assert.equal(validDate('2024-02-29'),true);});
