import {test,expect} from '@playwright/test';
import {spawn} from 'node:child_process';import {createInterface} from 'node:readline';import {resolve} from 'node:path';import {mkdirSync} from 'node:fs';
async function mcpClient(){const child=spawn(process.execPath,['mcp-server/server.mjs','--review-store',process.env.DESK_LOCAL_STORE!],{cwd:process.cwd(),stdio:['pipe','pipe','pipe']});let id=0;const pending=new Map<number,{resolve:(r:any)=>void,reject:(e:Error)=>void}>();const rl=createInterface({input:child.stdout});rl.on('line',line=>{const r=JSON.parse(line),p=pending.get(r.id);if(p){pending.delete(r.id);r.error?p.reject(Error(JSON.stringify(r.error))):p.resolve(r.result);}});const call=(method:string,params:unknown)=>new Promise<any>((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});child.stdin.write(JSON.stringify({jsonrpc:'2.0',id:n,method,params})+'\n');});await call('initialize',{protocolVersion:'2024-11-05',clientInfo:{name:'Synthetic browser acceptance',version:'1'},capabilities:{}});return {async tool(name:string,args:unknown={}){const r=await call('tools/call',{name,arguments:args});if(r.isError)throw Error(JSON.stringify(r));return JSON.parse(r.content[0].text);},close(){child.stdin.end();rl.close();child.kill();}};}
test('one company: evidence, actual MCP proposal, adopted work, revision, committee and recovery',async({page},info)=>{
 test.skip(!process.env.DESK_LOCAL_STORE,'Requires disposable local store');test.setTimeout(90000);
 const external:string[]=[];page.on('request',r=>{if(!new URL(r.url()).hostname.match(/^(localhost|127\.0\.0\.1)$/))external.push(r.url());});
 const company=`Pilot ${info.project.name} ${Date.now()}`;
 await page.goto('/');await page.getByRole('button',{name:'New deal',exact:true}).click();await page.getByLabel('Company',{exact:true}).fill(company);await page.getByRole('button',{name:'Create company workspace'}).click();await expect(page.getByRole('heading',{name:company,level:1})).toBeVisible();const url=page.url(),dealId=url.split('/').at(-1)!;
 await page.getByLabel('Reviewing as').fill('Avery Chen');await page.getByRole('navigation',{name:'Investment workspace'}).getByRole('button',{name:'Review',exact:true}).click();
 await page.getByLabel('Add company materials').setInputFiles({name:'Management note.txt',mimeType:'text/plain',buffer:Buffer.from('Revenue grew 20 percent.\nCustomer concentration needs investigation.')});
 await page.getByLabel('Source decision rationale').fill('Confirmed management-provided operating narrative.');await page.getByRole('button',{name:'Accept evidence',exact:true}).click();
 await page.getByRole('checkbox',{name:/Management note.txt/}).check();await page.getByRole('button',{name:'Release selected evidence'}).click();await expect(page.getByLabel('Model task')).toBeVisible();
 const client=await mcpClient();try{const releases=await client.tool('list_investment_reviews');const release=releases.find((r:any)=>r.deal_id===dealId);expect(release).toBeTruthy();const context=await client.tool('read_investment_evidence',release);const ref=context.evidence[0].id;
 await client.tool('propose_investment_work',{...release,company:undefined,kind:'finding',text:'Growth merits further diligence on revenue quality.',section:'Business',evidence_refs:[ref]});
 await client.tool('propose_investment_work',{...release,company:undefined,kind:'diligence',text:'Obtain customer concentration by ARR.',evidence_refs:[ref]});
 await page.getByRole('button',{name:'Collect model work'}).click();await page.locator('.proposal input[type=checkbox]').nth(0).check();await page.locator('.proposal input[type=checkbox]').nth(1).check();await page.getByRole('button',{name:'Adopt selected work'}).click();
 await page.getByRole('navigation',{name:'Investment workspace'}).getByRole('button',{name:'Brief',exact:true}).click();await expect(page.locator('.finding p').filter({hasText:'Growth merits further diligence on revenue quality.'})).toBeVisible();await page.getByLabel('Selected evidence',{exact:true}).selectOption([ref]);await page.getByLabel('Decision rationale',{exact:true}).fill('Customer schedule reconciled for this test.');await page.getByRole('button',{name:'Resolve with selected evidence'}).click();await expect(page.getByRole('button',{name:'Reopen question'})).toBeVisible();
 await page.getByRole('navigation',{name:'Investment workspace'}).getByRole('button',{name:'Review',exact:true}).click();await page.getByLabel('Delivery type').selectOption({label:'Replace Management note.txt'});await page.getByLabel('Add company materials').setInputFiles({name:'Revised management note.txt',mimeType:'text/plain',buffer:Buffer.from('Revenue grew 10 percent following restatement.\nCustomer concentration remains under review.')});await page.getByLabel('Source decision rationale').fill('Accepted documented operating restatement.');await page.getByRole('button',{name:'Accept evidence',exact:true}).click();await expect(page.getByText('Recheck the prior resolution against the revised source.',{exact:false})).toBeVisible();
 await page.getByRole('navigation',{name:'Investment workspace'}).getByRole('button',{name:'Brief',exact:true}).click();await expect(page.getByText(/Needs review after new evidence/)).toBeVisible();const nextRef=await page.getByLabel('Selected evidence',{exact:true}).locator('option').first().getAttribute('value');await page.getByLabel('Selected evidence',{exact:true}).selectOption(nextRef!);await page.getByLabel('Decision rationale',{exact:true}).fill('Growth finding remains conditional after restatement.');await page.getByRole('button',{name:'Reconcile with selected evidence'}).click();
 await page.getByRole('navigation',{name:'Investment workspace'}).getByRole('button',{name:'Committee',exact:true}).click();await page.getByRole('button',{name:'Prepare from current investment case'}).click();await expect(page.getByLabel('Working output')).toHaveValue(/Growth merits further diligence/);await page.getByRole('button',{name:'Save and reconcile output'}).click();await expect(page.getByRole('button',{name:'Download editable text'})).toBeEnabled();
 const textDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Download editable text'}).click();const file=await textDownload;expect(file.suggestedFilename()).toContain('Screening brief');await page.getByRole('button',{name:'Print / Save PDF',exact:true}).click();await expect(page.frameLocator('iframe[title="Print investment note"]').locator('pre')).toContainText('Revised management note.txt — Line 1');

 const out=resolve('../verification/deal-progress-20260908');mkdirSync(out,{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await expect(page.locator('.progress-rail')).toBeInViewport();await page.screenshot({path:resolve(out,`${info.project.name}-committee.png`),fullPage:true});await page.reload();await expect(page.getByRole('heading',{name:company,level:1})).toBeVisible();await page.getByRole('button',{name:'← Deals',exact:true}).click();await page.getByRole('button',{name:new RegExp('Open '+company)}).click();await expect(page.locator('.finding p').filter({hasText:'Growth merits further diligence on revenue quality.'})).toBeVisible();expect(external).toEqual([]);
 }finally{client.close();}
});

test('unfamiliar XLSX maps into the unified model and retains mappings across a revised delivery',async({page},info)=>{
 test.skip(!process.env.DESK_LOCAL_STORE,'Requires disposable store');
 const {zipSync,strToU8}=await import('fflate');
 function book(n:number){const files={'xl/workbook.xml':'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Board financials" sheetId="1" r:id="r1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<Relationships><Relationship Id="r1" Target="worksheets/sheet1.xml"/></Relationships>','xl/worksheets/sheet1.xml':`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="9"><c r="H9"><v>${n}</v></c></row></sheetData></worksheet>`};return Buffer.from(zipSync(Object.fromEntries(Object.entries(files).map(([k,v])=>[k,strToU8(v)]))));}
 await page.goto('/');await page.getByRole('button',{name:'New deal',exact:true}).click();await page.getByLabel('Company',{exact:true}).fill(`Workbook ${info.project.name} ${Date.now()}`);await page.getByLabel('Investment strategy',{exact:true}).selectOption('PE');await page.getByRole('button',{name:'Create company workspace'}).click();await page.getByLabel('Reviewing as').fill('Avery Chen');
 const nav=page.getByRole('navigation',{name:'Investment workspace'});await nav.getByRole('button',{name:'Review',exact:true}).click();await page.getByLabel('Add company materials').setInputFiles({name:'Board workbook.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:book(125)});
 await page.getByRole('button',{name:'Add metric',exact:true}).click();await page.getByLabel('Period ending 1',{exact:true}).fill('2025-12');await page.getByLabel('Source cell 1',{exact:true}).selectOption('H9');await page.getByLabel('Definition 1',{exact:true}).fill('Recognized software revenue');await page.getByLabel('Units',{exact:true}).selectOption('1000');await page.getByRole('button',{name:'Save mappings'}).click();await page.getByLabel('Source decision rationale').fill('Reviewed year-end actual revenue and reported units.');await page.getByRole('button',{name:'Accept evidence',exact:true}).click();await nav.getByRole('button',{name:'Model',exact:true}).click();await expect(page.getByRole('cell',{name:'125,000 USD',exact:true})).toBeVisible();
 await nav.getByRole('button',{name:'Review',exact:true}).click();await page.getByLabel('Delivery type').selectOption({label:'Replace Board workbook.xlsx'});await page.getByLabel('Add company materials').setInputFiles({name:'Revised board workbook.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:book(100)});await expect(page.getByLabel('Source cell 1',{exact:true})).toHaveValue('H9');await expect(page.getByRole('cell',{name:'-25000 (-20.0%)',exact:true})).toBeVisible();await page.getByLabel('Source decision rationale').fill('Confirmed reduced revenue after restatement.');await page.getByRole('button',{name:'Accept evidence',exact:true}).click();await nav.getByRole('button',{name:'Model',exact:true}).click();await expect(page.getByRole('cell',{name:'100,000 USD',exact:true})).toBeVisible();await page.getByRole('button',{name:'Board financials!H9',exact:true}).click();await expect(page.getByRole('dialog',{name:'Source inspector'})).toContainText('number: 100');await page.getByRole('button',{name:'Close source inspector'}).click();
 const out=resolve('../verification/deal-progress-20260908');mkdirSync(out,{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await expect(page.locator('.progress-rail')).toBeInViewport();await page.screenshot({path:resolve(out,`${info.project.name}-model.png`),fullPage:true});
});
