import {File as NodeFile} from 'node:buffer';
const File=NodeFile as unknown as typeof globalThis.File;
import {describe,it,expect} from 'vitest';import {zipSync,strToU8} from 'fflate';import {freshDeal,sourceFromFile,confirmMapping,decideSource,metricChanges,changeWorkbook,outputText,type ProgressDeal} from './deal-progress';import {readWorkbook} from './workbook-diff';
const wb=()=>{const files={'xl/workbook.xml':'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Odd layout" sheetId="1" r:id="r1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<Relationships><Relationship Id="r1" Target="worksheets/sheet1.xml"/></Relationships>','xl/worksheets/sheet1.xml':'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="7"><c r="D7"><v>100</v></c><c r="F7"><f>D7*0.2</f><v>20</v></c></row></sheetData></worksheet>'};return new File([zipSync(Object.fromEntries(Object.entries(files).map(([k,v])=>[k,strToU8(v)]))) as BlobPart],'Unfamiliar board workbook.xlsx');};
describe('unified investment review',()=>{
 it('maps unfamiliar cells with explicit definitions and stored formula provenance',async()=>{const s=await sourceFromFile(wb());const mapped=confirmMapping(s,'Odd layout','USD',1000,[{metric:'revenue',period:'2025-12',basis:'actual',address:'D7',definition:'Recognized product revenue'},{metric:'adjustedEbitda',period:'2025-12',basis:'forecast',address:'F7',definition:'Includes management addbacks'}]);expect(mapped.mapping!.rows.map(r=>r.value)).toEqual([100000,20000]);expect(mapped.excerpts.find(e=>e.locator==='Odd layout!F7')!.text).toContain('stored result, not recalculated');expect(()=>confirmMapping(s,'Odd layout','USD',1,[{metric:'revenue',period:'2025-13',basis:'actual',address:'D7',definition:'Revenue'}])).toThrow(/month/);});
 it('revisions reopen linked resolutions, preserve source bytes and mark outputs stale',async()=>{let d=freshDeal('Company','PE','What supports the price?','Initial screen');const first=await sourceFromFile(new File(['Base narrative'],'initial.txt'));d.sources=[first];d=decideSource(d,first.id,'accepted','Analyst','Reviewed');const ref=first.excerpts[0].id;d.findings=[{id:'f1',section:'Business',text:'Conditional growth',refs:[ref],author:'Analyst',state:'current',sourceVersion:1}];d.issues=[{id:'i1',question:'Validate growth',why:'Changes valuation',owner:'Analyst',next:'Done',target:'f1',status:'resolved',resolution:'Base version reconciled',refs:[ref]}];d.outputs={'Screening brief':{text:'Old output',stale:false,sourceVersion:1}};const next=await sourceFromFile(new File(['Revised narrative'],'revised.txt'),first.id);d.sources.push(next);const rejected=decideSource(d,next.id,'rejected','Analyst','Not supported');expect(rejected.sourceVersion).toBe(1);expect(rejected.issues[0].status).toBe('resolved');const accepted=decideSource(d,next.id,'accepted','Analyst','Reconciled update');expect(accepted.sourceVersion).toBe(2);expect(accepted.sources[0].bytes).toBe(first.bytes);expect(accepted.findings[0].state).toBe('changed');expect(accepted.issues[0].status).toBe('working');expect(accepted.outputs['Screening brief'].stale).toBe(true);});
 it('does not compare unlike definitions and reports removed metrics as missing, not zero',async()=>{const s=await sourceFromFile(wb());const rows=[{metric:'revenue' as const,period:'2025',basis:'actual' as const,address:'D7',definition:'Revenue'}];const a=confirmMapping(s,'Odd layout','USD',1,rows),b=confirmMapping({...s,id:'new',replaces:s.id},'Odd layout','USD',1,[{...rows[0],definition:'Changed recognition basis'}]);const d={...freshDeal('Company','VC / Growth','Question','Initial screen'),sources:[a,b]};expect(metricChanges(d,b)[0].change).toBeNull();const missing={...b,mapping:{...b.mapping!,rows:[]}};expect(metricChanges(d,missing)[0].after).toBeNull();expect(metricChanges(d,missing)[0].meaning).toMatch(/missing/);});
 it('exports a readable XLSX and excludes stale findings from current conclusions',()=>{const d=freshDeal('=NOT_A_FORMULA','PE','Question','Initial screen');d.findings=[{id:'f',section:'Business',text:'Stale claim',refs:[],author:'Analyst',state:'changed',sourceVersion:0}];expect(outputText(d,'Screening brief')).not.toContain('Stale claim');expect(readWorkbook(changeWorkbook(d)).get('Review changes')!.get('A1')!.value).toBe('Metric');});
 it('exports human-readable citations, contradictory conclusions and only changes after the last saved update',async()=>{const d=freshDeal('Company','PE','Question','Initial screen');const source=await sourceFromFile(new File(['Management statement'],'Management update.txt'));source.status='accepted';d.sources=[source];d.findings=[{id:'f',section:'Business',text:'Current business case',refs:[source.excerpts[0].id],author:'Analyst',state:'current',sourceVersion:1},{id:'f2',section:'Merits',text:'Prior claim contradicted',refs:[source.excerpts[0].id],author:'Analyst',state:'contradicted',sourceVersion:1}];d.events=[{action:'Old change',actor:'Analyst',at:'2026-09-01'},{action:'New change',actor:'Analyst',at:'2026-09-08'}];d.outputs['Partner update']={text:'Prior update',sourceVersion:1,stale:true,eventCount:1};const note=outputText(d,'Partner update');expect(note).toContain('Management update.txt — Line 1');expect(note).not.toContain(source.excerpts[0].id);expect(note).toContain('Prior claim contradicted');expect(note).not.toContain('Old change');expect(note).toContain('New change');});

});

it('leads a partner update with the adopted view and compacts missing sections without inventing them',()=>{const d=freshDeal('Sample','PE','Question','Initial screen');d.findings=[{id:'view',section:'Current view',text:'Hold pending cash explanation',refs:[],author:'Analyst',state:'current',sourceVersion:0},{id:'business',section:'Business',text:'Software business',refs:[],author:'Analyst',state:'current',sourceVersion:0}];const text=outputText(d,'Partner update');expect(text.indexOf('Hold pending cash explanation')).toBeLessThan(text.indexOf('Software business'));expect(text).toContain('Not yet established: Next action; Concerns; Contradictory evidence; Merits.');expect(text).not.toContain('Not yet established.\n\n');});
