import {readWorkbook} from './workbook-diff';
import {sha256} from './intake';
import {strToU8,zipSync} from 'fflate';
import type {WorkbookReview} from './workbook-intake';
export type MetricKind='revenue'|'ebitda'|'adjustedEbitda'|'cash'|'debt'|'operatingCashFlow';
export const metricNames:Record<MetricKind,string>={revenue:'Revenue',ebitda:'Reported EBITDA',adjustedEbitda:'Adjusted EBITDA',cash:'Cash',debt:'Debt',operatingCashFlow:'Operating cash flow'};
export interface MappingRow {period:string;basis:'actual'|'forecast'|'unconfirmed';metric:MetricKind;address:string;ref:string;value:number;definition:string}
export interface EvidenceSource {id:string;name:string;kind:'xlsx'|'pdf'|'text';bytes:string;digest:string;status:'pending'|'accepted'|'rejected'|'deferred'|'superseded';replaces:string|null;note:string;excerpts:{id:string;locator:string;text:string}[];mapping:{sheet:string;currency:string;scale:number;rows:MappingRow[]}|null}
export interface Finding {id:string;section:string;text:string;refs:string[];author:string;state:'current'|'changed'|'contradicted'|'unsupported';sourceVersion:number;proposalId?:string}
export interface Diligence {id:string;question:string;why:string;owner:string;next:string;target:string;status:'blocker'|'working'|'resolved';resolution:string;refs:string[]}
export interface ProgressDeal {schema:'desk.deal-progress/v1';id:string;company:string;strategy:'PE'|'VC / Growth';stage:'Initial screen'|'Active diligence'|'Committee preparation';question:string;sourceVersion:number;updatedAt:string;sources:EvidenceSource[];findings:Finding[];issues:Diligence[];assumptions:{id:string;text:string;owner:string;refs:string[]}[];events:{action:string;actor:string;at:string}[];outputs:Record<string,{text:string;sourceVersion:number;stale:boolean;eventCount?:number}>}
export interface ProgressSnapshot {version:number;state:ProgressDeal}
export interface ProgressProposal {id:string;kind:'finding'|'diligence'|'diligence_update'|'memo';text:string;refs:string[];section:string;target:string;sourceVersion:number;release_digest:string;current:boolean;why?:string;next?:string}
export interface ProgressRow {id:string;version:number;company:string;strategy:string;stage:string;question:string;updatedAt:string;openIssues:number;next:string}
declare global {interface Window {__DESK_SESSION__?:string}}
export async function progressApi(body?:unknown,deal?:string){if(!window.__DESK_SESSION__)throw Error('Start the local Desk to save or open private company workspaces.');const response=await fetch(`/__desk/progress${deal?`?deal=${encodeURIComponent(deal)}`:''}`,{method:body?'POST':'GET',headers:{'x-desk-session':window.__DESK_SESSION__,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(30000)});const result=await response.json();if(!response.ok)throw Error(response.status===409?'Another window changed this deal. Reload the latest version before saving.':result.error??'Local save failed');return result;}
export function freshDeal(company:string,strategy:ProgressDeal['strategy'],question:string,stage:ProgressDeal['stage']):ProgressDeal{return {schema:'desk.deal-progress/v1',id:`deal-${crypto.randomUUID()}`,company:company.trim(),strategy,stage,question:question.trim(),sourceVersion:0,updatedAt:new Date().toISOString(),sources:[],findings:[],issues:[],assumptions:[],events:[],outputs:{}};}
export function bytesToBase64(bytes:ArrayBuffer){let value='';const a=new Uint8Array(bytes);for(let i=0;i<a.length;i+=32768)value+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(value);}
export function fromBase64(value:string){return Uint8Array.from(atob(value),c=>c.charCodeAt(0)).buffer;}
export async function sourceFromFile(file:File,replaces:string|null=null):Promise<EvidenceSource>{if(file.size>8*1024*1024)throw Error('Each source must be under 8 MB.');const bytes=await file.arrayBuffer(),id=`src-${crypto.randomUUID()}`,ext=file.name.split('.').at(-1)?.toLowerCase();const source:EvidenceSource={id,name:file.name,kind:ext==='xlsx'?'xlsx':ext==='pdf'?'pdf':'text',bytes:bytesToBase64(bytes),digest:await sha256(bytes),status:'pending',replaces,note:'',excerpts:[],mapping:null};
 if(ext==='xlsx'){const sheets=readWorkbook(bytes,{inspectionOnly:true});for(const [sheet,cells] of sheets)for(const [address,cell] of cells){if(source.excerpts.length>=10000)throw Error('Workbook exceeds the 10,000 populated-cell review limit; provide a relevant extract. Original file was not changed.');source.excerpts.push({id:`${id}:${source.excerpts.length}`,locator:`${sheet}!${address}`,text:`${cell.type}: ${cell.value}${cell.formula?`; formula =${cell.formula}; stored result, not recalculated`:''}`});}source.note='Original cells and formulas preserved. Stored Excel results are not recalculated. Confirm financial definitions, units and actual/forecast periods.';}
 else if(ext==='pdf'){const {getDocument,GlobalWorkerOptions}=await import('pdfjs-dist/legacy/build/pdf.mjs');GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/legacy/build/pdf.worker.min.mjs',import.meta.url).toString();const task=getDocument({data:new Uint8Array(bytes.slice(0))});try{const doc=await task.promise;if(doc.numPages>100)throw Error('Choose a PDF of up to 100 pages.');for(let p=1;p<=doc.numPages;p++){const page=await doc.getPage(p),content=await page.getTextContent();const text=content.items.map(i=>'str'in i?i.str:'').join(' ');for(let offset=0;offset<text.length;offset+=6000)source.excerpts.push({id:`${id}:${source.excerpts.length}`,locator:`Page ${p}, text segment ${1+offset/6000}`,text:text.slice(offset,offset+6000)});}if(!source.excerpts.length)throw Error('No PDF text found. OCR is not available; provide a text-bearing document.');source.note='PDF text extracted by page; images and charts are retained in the original, not interpreted.';}finally{await task.destroy();}}
 else if(['txt','md','csv'].includes(ext??'')){const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);const lines=text.split(/\r?\n/);for(let i=0;i<lines.length;i++){if(lines[i].length>12000)throw Error('A text line exceeds the supported excerpt size.');if(lines[i].trim())source.excerpts.push({id:`${id}:${source.excerpts.length}`,locator:`Line ${i+1}`,text:lines[i]});}source.note=ext==='csv'?'CSV preserved as source lines; financial definitions require explicit mapping in an XLSX workbook.':'Original text retained with line references.';}
 else throw Error('Supported sources: XLSX, text-bearing PDF, CSV, TXT and Markdown.');
 if(source.excerpts.length>10000||source.excerpts.reduce((n,e)=>n+e.text.length,0)>2_000_000)throw Error('Source text exceeds the review limit; provide a relevant extract.');return source;}
export function confirmMapping(source:EvidenceSource,sheet:string,currency:string,scale:number,rows:Omit<MappingRow,'ref'|'value'>[]):EvidenceSource{if(![1,1000,1000000].includes(scale)||!['USD','EUR','GBP','CAD','AUD'].includes(currency))throw Error('Confirm currency and units.');const cells=readWorkbook(fromBase64(source.bytes),{inspectionOnly:true}).get(sheet);if(!cells)throw Error('Worksheet unavailable.');const keys=new Set<string>();const mapped=rows.map(row=>{if(!row.period.trim()||!/^\d{4}(-\d{2}(-\d{2})?)?$/.test(row.period)||!row.definition.trim())throw Error('Use a period ending YYYY, YYYY-MM or YYYY-MM-DD and record the metric definition.');if(!metricNames[row.metric])throw Error('Unknown metric');if(!['actual','forecast'].includes(row.basis))throw Error('Confirm actual versus forecast for each period.');const parts=row.period.split('-').map(Number);if(parts.length>1&&(parts[1]<1||parts[1]>12))throw Error('Invalid period month.');if(parts.length>2&&(parts[2]<1||parts[2]>new Date(Date.UTC(parts[0],parts[1],0)).getUTCDate()))throw Error('Invalid period day.');const key=`${row.metric}:${row.period}:${row.basis}`;if(keys.has(key))throw Error('A metric/period/basis can only be mapped once.');keys.add(key);const cell=cells.get(row.address),ref=source.excerpts.find(e=>e.locator===`${sheet}!${row.address}`)?.id;if(cell?.type!=='number'||!ref||!Number.isFinite(Number(cell.value)*scale)||Math.abs(Number(cell.value)*scale)>Number.MAX_SAFE_INTEGER/100)throw Error(`Cell ${row.address} has no supported numeric result.`);return {...row,ref,value:Number(cell.value)*scale};});return {...source,mapping:{sheet,currency,scale,rows:mapped}};}
export function decideSource(deal:ProgressDeal,sourceId:string,outcome:'accepted'|'rejected'|'deferred',actor:string,reason:string){if(!actor.trim()||!reason.trim())throw Error('A reviewer and decision rationale are required.');const src=deal.sources.find(s=>s.id===sourceId);if(!src||!['pending','deferred'].includes(src.status))throw Error('This source is no longer awaiting review.');const old=src.replaces?deal.sources.find(s=>s.id===src.replaces):null;if(src.replaces&&old?.status!=='accepted')throw Error('The baseline changed; compare against the current source.');const now=new Date().toISOString(),changed=new Set(old?.excerpts.map(e=>e.id)??[]),nextVersion=deal.sourceVersion+(outcome==='accepted'?1:0);return {...deal,sourceVersion:nextVersion,updatedAt:now,sources:deal.sources.map(s=>s.id===sourceId?{...s,status:outcome,note:`${s.note}\n${actor}: ${reason}`} :outcome==='accepted'&&s.id===src.replaces?{...s,status:'superseded' as const}:s),findings:deal.findings.map(f=>outcome==='accepted'&&(!old||f.refs.some(r=>changed.has(r)))?{...f,state:'changed' as const}:f),issues:deal.issues.map(i=>outcome==='accepted'&&i.status==='resolved'&&i.refs.some(r=>changed.has(r))?{...i,status:'working' as const,next:'Recheck the prior resolution against the revised source.'}:i),outputs:Object.fromEntries(Object.entries(deal.outputs).map(([k,v])=>[k,{...v,stale:outcome==='accepted'||v.stale}])),events:[...deal.events,{action:`${outcome}: ${src.name}. ${reason}`,actor,at:now}]};}
export function metricChanges(deal:ProgressDeal,source:EvidenceSource){
 const prior=deal.sources.find(s=>s.id===source.replaces),previous=prior?.mapping?.rows??[],current=source.mapping?.rows??[];
 const results=current.map(row=>{const before=previous.find(r=>r.metric===row.metric&&r.period===row.period&&r.basis===row.basis);const comparable=Boolean(before&&prior?.mapping?.currency===source.mapping?.currency&&before.definition===row.definition);return {metric:metricNames[row.metric],period:row.period,basis:row.basis,currency:source.mapping!.currency,before:comparable?before!.value:null,after:row.value as number|null,change:comparable?row.value-before!.value:null,percent:comparable&&before!.value!==0?(row.value/before!.value-1)*100:null,ref:row.ref,meaning:before&&!comparable?'Definition or currency changed; comparison requires review.':!before?'New mapped evidence':'Mapped change; assess materiality in the investment case.'};});
 for(const row of previous)if(!current.some(r=>r.metric===row.metric&&r.period===row.period&&r.basis===row.basis))results.push({metric:metricNames[row.metric],period:row.period,basis:row.basis,currency:prior!.mapping!.currency,before:row.value,after:null,change:null,percent:null,ref:row.ref,meaning:'Previously mapped metric is missing. Do not treat the missing value as zero.'});return results;
}

export function evidenceLabel(deal:ProgressDeal,ref:string){
 for(const source of deal.sources){const excerpt=source.excerpts.find(e=>e.id===ref);if(excerpt)return `${source.name} — ${excerpt.locator}${source.status==='superseded'?' (prior version)':''}`;}
 return 'Source unavailable';
}
export function outputText(deal:ProgressDeal,kind:string){
 const current=deal.findings.filter(f=>f.state==='current');
 const citations=(refs:string[])=>refs.map(ref=>evidenceLabel(deal,ref)).join('; ')||'Analyst judgment; no cited evidence';
 const text=[`${deal.company} — ${kind}`,`${deal.strategy} · ${deal.stage} · Evidence version ${deal.sourceVersion}`,`Investment question: ${deal.question}`,''];
 if(kind==='Management questions'){
  for(const status of ['blocker','working'])for(const i of deal.issues.filter(i=>i.status===status))text.push(`[${status==='blocker'?'Decision blocker':'In progress'}] ${i.question}`,`Why: ${i.why}`,`Owner: ${i.owner||'Unassigned'} · Next: ${i.next}`,`Affected conclusion: ${deal.findings.find(f=>f.id===i.target)?.text??deal.assumptions.find(a=>a.id===i.target)?.text??'Not linked'}`,`Evidence: ${citations(i.refs)}`,'');
 }else{
  for(const section of ['Business','Merits','Concerns','Contradictory evidence','Current view','Next action']){
   const findings=current.filter(f=>f.section===section);text.push(section);
   text.push(...(findings.length?findings.map(f=>`${f.text}\nEvidence: ${citations(f.refs)}`):['Not yet established.']),'');
  }
  const contradicted=deal.findings.filter(f=>f.state==='contradicted');
  if(contradicted.length)text.push('Prior conclusions now contradicted',...contradicted.map(f=>`${f.text}\nPrior support: ${citations(f.refs)}`),'');
  text.push('Remaining diligence',...deal.issues.filter(i=>i.status!=='resolved').map(i=>`${i.question} — ${i.owner||'Unassigned'}: ${i.next}`));
  if(kind==='Partner update'){
   const since=deal.outputs[kind]?.eventCount??0;
   text.push('',since?'Changes since previous saved partner update':'Review history to date',...deal.events.slice(since).map(e=>`${e.at}: ${e.action.replace(/Adopted proposal [0-9a-f-]+/g,'Adopted model finding or diligence work')} (${e.actor})`));
  }
 }
 text.push('','Financial evidence',...deal.sources.filter(s=>s.status==='accepted'&&s.mapping).flatMap(s=>s.mapping!.rows.map(r=>`${metricNames[r.metric]} · ${r.period} ${r.basis}: ${r.value.toLocaleString('en-US')} ${s.mapping!.currency} · ${s.name} — ${s.mapping!.sheet}!${r.address} · ${r.definition}`)),'','Transaction implications',deal.strategy==='PE'?'Leverage, price and returns require verified transaction inputs or the original Excel model; uploaded operating metrics do not establish an LBO.':'Ownership, dilution and financing outcomes require verified terms or the original Excel model; uploaded operating metrics do not establish a VC return.','','Source register',...deal.sources.filter(s=>s.status==='accepted').map(s=>s.name),'','Working investment analysis; human judgment required.');
 return text.join('\n');
}

const xml=(x:unknown)=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function changeWorkbook(deal:ProgressDeal){const rows:unknown[][]=[['Metric','Period','Basis','Currency','Previous','Revised','Change','Change %','Source reference']];for(const src of deal.sources.filter(s=>s.status==='accepted'&&s.replaces))for(const c of metricChanges(deal,src))rows.push([c.metric,c.period,c.basis,c.currency,c.before,c.after,c.change,c.percent,evidenceLabel(deal,c.ref)]);const sheet=rows.map((r,i)=>`<row r="${i+1}">${r.map((c,j)=>`<c r="${String.fromCharCode(65+j)}${i+1}" ${typeof c==='number'?'':'t="inlineStr"'}>${typeof c==='number'?`<v>${c}</v>`:`<is><t xml:space="preserve">${xml(c)}</t></is>`}</c>`).join('')}</row>`).join('');const files={'[Content_Types].xml':'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>','_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="r1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml':'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Review changes" sheetId="1" r:id="r1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="r1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>','xl/worksheets/sheet1.xml':`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${sheet}</sheetData></worksheet>`};return zipSync(Object.fromEntries(Object.entries(files).map(([k,v])=>[k,strToU8(v)]))).buffer as ArrayBuffer;}
export async function migrateWorkbook(review:WorkbookReview){const deal=freshDeal(review.name,'VC / Growth','What does the operating evidence support, and what diligence remains?','Initial screen');deal.id=`migrated-${review.id}`;const src=await sourceFromFile(new File([review.bytes],review.filename));src.status='accepted';src.note=review.rationale;const cells=readWorkbook(review.bytes,{inspectionOnly:true}).get(review.sheet)!;const rows:MappingRow[]=[];for(const m of review.mappings)for(const [metric,address] of [['revenue',m.revenue],['ebitda',m.earnings]] as const){if(!address)continue;rows.push({period:m.period,basis:'unconfirmed',metric,address,ref:src.excerpts.find(e=>e.locator===`${review.sheet}!${address}`)!.id,value:Number(cells.get(address)!.value)*review.scale,definition:'Legacy mapping — confirm actual/forecast classification and period dates before using.'});}src.mapping={sheet:review.sheet,currency:review.currency,scale:review.scale,rows};deal.sources=[src];for(const h of review.history){const old=await sourceFromFile(new File([h.bytes],h.filename));old.status=h.outcome==='Rejected'?'rejected':'superseded';old.note=`${h.reviewer}: ${h.rationale}`;deal.sources.push(old);}deal.sourceVersion=review.version;deal.events=[{action:'Imported legacy operating review. Original browser record retained; confirm financial definitions.',actor:review.reviewer,at:review.approvedAt}];return deal;}
