import {useEffect,useState,type ReactNode} from 'react';
import './desktop-onboarding.css';
type Status={version:string;completed:boolean;verified:boolean};
type Challenge={code:string;expires:number};
async function request<T>(action?:string):Promise<T>{const runtime=window as unknown as {__DESK_SESSION__:string};const res=await fetch('/__desk/desktop',{method:action?'POST':'GET',headers:{'x-desk-session':runtime.__DESK_SESSION__,'Content-Type':'application/json'},...(action?{body:JSON.stringify({action})}:{})});const result=await res.json();if(!res.ok)throw Error(result.error||'Reopen Underwriting Desk and try again.');return result;}
export function DesktopOnboarding({children}:{children:ReactNode}){
 const [status,setStatus]=useState<Status|null>(null),[open,setOpen]=useState(false),[challenge,setChallenge]=useState<Challenge|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[closed,setClosed]=useState(false);
 useEffect(()=>{const show=()=>setOpen(true);window.addEventListener("desk-open-setup",show);return()=>window.removeEventListener("desk-open-setup",show);},[]);
 async function refresh(){const next=await request<Status>();setStatus(next);return next;}
 useEffect(()=>{request<Status>().then(next=>{setStatus(next);setOpen(!next.completed);}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!challenge||!open)return;const timer=setInterval(()=>{refresh().catch(e=>setError(e.message));},2000);return()=>clearInterval(timer);},[challenge,open]);
 async function act(action:string){setBusy(true);setError('');try{if(action==='test'){setChallenge(await request<Challenge>('test'));await refresh();}else if(action==='complete'){await request('complete');await refresh();setOpen(false);}else if(action==='quit'){await request('quit');setClosed(true);}else{await request(action);setNotice('Approve the Underwriting Desk extension in Claude, then return here to test the connection.');}}catch(e){setError(e instanceof Error?e.message:'Unable to complete setup.');}finally{setBusy(false);}}
 const prompt=challenge?'Use the Underwriting Desk tool verify_desk_connection with code "'+challenge.code+'". This is a connection test only; do not read any company materials.':'';
 if(closed)return <main className="desktop-welcome"><h1>Underwriting Desk is closed</h1><p>Your saved work remains on this computer. Open the application to return.</p></main>;
 return <><div className="desktop-control"><span>Underwriting Desk · Local workspace</span><button onClick={()=>setOpen(true)}>Connection setup</button><button onClick={()=>act('quit')}>Quit Desk</button></div>{status?.completed?<div hidden={open}>{children}</div>:null}{(!status||open)&&<main className="desktop-welcome"><div className="desktop-wordmark">UNDERWRITING DESK</div><h1>Your investment workspace.<br/>Ready on this computer.</h1><p className="desktop-lead">Connect your existing Claude subscription, then start a company review. The Desk keeps the investment case; Claude helps you work through it.</p><ol className="desktop-steps"><li><span>1</span><div><h2>Workspace ready</h2><p>The application includes its own runtime. Your deal records are saved locally.</p></div><strong>Ready</strong></li><li><span>2</span><div><h2>Connect Claude Desktop</h2><p>Open the extension and approve it in Claude. Your organization may need to allow custom desktop extensions.</p><button disabled={busy||!status} onClick={()=>act('connect')}>Open Claude extension</button>{notice&&<p role="status">{notice}</p>}</div></li><li><span>3</span><div><h2>Check the connection</h2><p>Run a short test in a new Claude conversation. No company materials are shared.</p><button disabled={busy||!status} onClick={()=>act('test')}>{challenge?'Start a fresh test':'Create connection test'}</button>{challenge&&<><label htmlFor="desk-test-prompt">Paste this into Claude</label><textarea id="desk-test-prompt" readOnly value={prompt} rows={3}/><button onClick={()=>navigator.clipboard.writeText(prompt).then(()=>setNotice('Test prompt copied.')).catch(()=>setError('Select and copy the test prompt above.'))}>Copy test prompt</button><p role="status">{status?.verified?'Connection verified. You can start your first review.':'Waiting for the test response. This code expires after 10 minutes.'}</p></>}</div>{status?.verified&&<strong>Verified</strong>}</li></ol>{error&&<p role="alert">{error} <button onClick={()=>refresh().then(next=>setOpen(!next.completed)).catch(e=>setError(e.message))}>Retry</button></p>}<footer><button className="desktop-primary" disabled={!status||busy} onClick={()=>act('complete')}>{status?.verified?'Open my workspace':'Continue without Claude'}</button><p>You can connect later. In the Desk, you choose which evidence to release and review every model proposal.</p></footer></main>}</>;
}
