import {registeredMetric} from "./data-contract";
import type {CaseData, Metric, PECaseResult, PESensitivityCell, VCSensitivityCell, VCScenarioResult} from "./types";
import type {DealWorkspaceState} from "./workspace-state";

type OpenMetric = (metric: Metric, trigger: HTMLElement) => void;
type UpdateWorkspace = (patch: Partial<DealWorkspaceState>) => void;

const money = (cents: number) => new Intl.NumberFormat("en-US", {style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 1}).format(cents / 100);
const percent = (value: string | number) => `${(Number(value) * 100).toFixed(1)}%`;
const multiple = (value: string | number) => `${Number(value).toFixed(2)}x`;
const titleCaseIdentifier = (value: string) => value.replaceAll("_", " ").replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const holderLabel = (value: string) => ({"series-a-investor": "Series A investors", founders: "Founders", employees: "Employees"}[value] ?? titleCaseIdentifier(value));
const classLabel = (value: string) => ({SERIES_A: "Series A", COMMON: "Common"}[value] ?? titleCaseIdentifier(value));

export interface ScenarioMemoSummary {
  state: "Canonical case" | "Unapproved what-if" | "Accepted revision" | "Revision awaiting disposition";
  label: string;
  returnLine: string;
  detail: string;
  snapshotId: string;
  sectionBodies: Record<string, string>;
  reconciliationBlockedReason?: string;
}

export function scenarioMemoSummary(caseData: CaseData, state: Pick<DealWorkspaceState, "scenarioValues"> & Partial<Pick<DealWorkspaceState, "changeControl">>): ScenarioMemoSummary {
  if (caseData.peEngine) {
    const key = (["ask", "selected", "downside"] as const).includes(state.scenarioValues.peScenario as "ask" | "selected" | "downside") ? state.scenarioValues.peScenario as "ask" | "selected" | "downside" : "selected";
    const labels = {ask: "Seller ask", selected: "Selected terms", downside: "Downside"};
    const result = caseData.peEngine[key];
    const change = state.changeControl;
    const disposition = change?.dispositionEvents.at(-1)?.disposition;
    if (change && disposition !== "REJECTED") {
      const rerun = caseData.peEngine.sensitivities.one_way.find((cell) => cell.result_receipt_sha256 === change.deterministicReceiptSha256);
      if (!rerun) throw new Error("Revision is not bound to a retained deterministic rerun");
      const returnLine = `${percent(rerun.gross_xirr)} annualized gross return · ${multiple(rerun.gross_moic)} gross multiple`;
      const awaiting = disposition !== "ACCEPTED";
      return {
        state: awaiting ? "Revision awaiting disposition" : "Accepted revision",
        label: change.toVersion,
        returnLine,
        detail: `${money(rerun.ending_debt_cents)} exit debt after the evidence-bound rerun. Version 1 remains preserved in the audit record.`,
        snapshotId: awaiting ? `pe:change-pending:${change.changeSetId}` : `pe:change-accepted:${change.changeSetId}:${rerun.result_receipt_sha256}`,
        reconciliationBlockedReason: awaiting ? "A named reviewer must accept or reject the revision before the memo can be reconciled." : undefined,
        sectionBodies: {
          recommendation: `REOPEN DILIGENCE. The accepted ${change.toVersion} retention revision produces ${returnLine}, below the declared 22.0% annualized-return screen. Do not advance the selected terms until the reopened retention work is resolved.`,
          economics: `${change.toVersion} evidence-bound rerun: ${returnLine}, with ${money(rerun.ending_debt_cents)} of exit debt. The prior Version 1 selected case is preserved but is no longer the accepted working evidence state.`,
          downside: `${change.changeTitle}. ${change.decisionConsequence} The revision does not itself resolve diligence or authorize an investment decision.`,
        },
      };
    }
    const returnLine = `${percent(result.gross_xirr)} annualized gross return · ${multiple(result.gross_moic)} gross multiple`;
    const recommendation = key === "ask"
      ? `REPRICE. Seller ask produces ${returnLine}, below the declared 22.0% annualized-return screen. Do not advance at asking terms.`
      : key === "downside"
        ? `REPRICE remains conditional. The retained downside produces ${returnLine}; the committee should not advance without preserving the declared downside protections.`
        : `REPRICE. Selected terms produce ${returnLine} and clear the declared point-return screen, subject to unresolved diligence and human investment-committee approval.`;
    return {state: key === "selected" ? "Canonical case" : "Unapproved what-if", label: labels[key], returnLine, detail: `${money(result.debt_schedule.ending_debt_cents)} exit debt. This selected working scenario does not overwrite the canonical case.`, snapshotId: `pe:${key}:${result.receipt_sha256}`, sectionBodies: {
      recommendation,
      economics: `${labels[key]}: ${returnLine}. Exit equity value is ${money(result.exit_equity_value_cents)} with ${money(result.debt_schedule.ending_debt_cents)} of exit debt and ${money(result.debt_schedule.minimum_liquidity_cents)} of minimum liquidity.`,
      downside: `${result.debt_schedule.first_covenant_breach_month ? `A modeled covenant breach begins in month ${result.debt_schedule.first_covenant_breach_month}.` : "No covenant breach is modeled in this retained scenario."} The result remains conditional on retention, margin quality, concentration, debt terms, and unresolved diligence.`,
    }};
  }
  const keys = ["base", "milestone", "downside", "financing_shortfall"] as const;
  const key = keys.includes(state.scenarioValues.vcScenario as typeof keys[number]) ? state.scenarioValues.vcScenario as typeof keys[number] : "milestone";
  const labels = {base: "Tranche withheld", milestone: "Milestone funded", downside: "Down round", financing_shortfall: "Financing shortfall"};
  const result = caseData.vcEngine![key];
  const engine = caseData.vcEngine!;
  const riskCell = engine.risk_sensitivity.cells.find((item) => item.cell_id === state.scenarioValues.vcRiskCell) ?? engine.risk_sensitivity.cells.find((item) => item.cell_id === engine.risk_sensitivity.canonical_cell_id)!;
  const policyThreshold = engine.risk_sensitivity.policy_threshold_choices.includes(state.scenarioValues.vcLossPolicy) ? state.scenarioValues.vcLossPolicy : engine.risk_sensitivity.canonical_policy_threshold;
  const isCanonical = key === "milestone" && riskCell.cell_id === engine.risk_sensitivity.canonical_cell_id && policyThreshold === engine.risk_sensitivity.canonical_policy_threshold;
  const policyResult = Number(riskCell.catastrophe_probability) <= Number(policyThreshold) ? "clears" : "misses";
  const returnLine = `${percent(result.gross_xirr)} annualized gross return · ${multiple(result.gross_moic)} gross multiple`;
  const detail = `${percent(result.target_ownership)} investor ownership · ${money(result.minimum_cash_cents)} minimum cash · the selected ${percent(riskCell.catastrophe_probability)} loss-case probability ${policyResult} the ${percent(policyThreshold)} Desk maximum. Every severe-loss path loses in this retained structure; the replay checks the scenario generator rather than estimating the probability.`;
  return {state: isCanonical ? "Canonical case" : "Unapproved what-if", label: labels[key], returnLine, detail, snapshotId: `vc:${key}:${result.receipt_sha256}:${riskCell.receipt_sha256}:${policyThreshold}`, sectionBodies: {
    recommendation: `HOLD under the selected synthetic scenario and unreviewed policy. ${labels[key]} produces ${returnLine}, but the selected ${percent(riskCell.catastrophe_probability)} loss-case probability ${policyResult} the ${percent(policyThreshold)} Desk maximum.`,
    economics: `${labels[key]}: ${returnLine}, ${percent(result.target_ownership)} investor ownership, and ${money(result.minimum_cash_cents)} minimum cash.`,
    downside: `The selected loss-case probability is an analyst assumption, not an empirical forecast. Every severe-loss path in this retained structure returns below 1.0x. Reconsideration requires reviewed policy, verified financing terms, ordinary-cohort evidence, and completed diligence.`,
  }};
}

function registryMetric(caseData: CaseData, metricId: string, detail: string, label?: string): Metric {
  const registry = registeredMetric(caseData, metricId);
  return {metric_id: metricId, label: label ?? registry.label, value: registry.display_value, detail, classification: registry.classification, lineage: registry.source_locator_ids, registry};
}

function MetricButton({caseData, metricId, detail, label, openMetric}: {caseData: CaseData; metricId: string; detail: string; label?: string; openMetric: OpenMetric}) {
  const metric = registryMetric(caseData, metricId, detail, label);
  return <button type="button" className="finance-kpi" data-metric-id={metricId} onClick={(event) => openMetric(metric, event.currentTarget)}><span>{metric.label}</span><strong>{metric.value}</strong><small>View source</small></button>;
}

function ReturnDistribution({caseData, openMetric}: {caseData: CaseData; openMetric: OpenMetric}) {
  const metrics = caseData.returnsDistribution.moic.map((_, index) => registeredMetric(caseData, caseData.caseId === "helios" ? `helios-distribution-moic-${index}` : `${caseData.caseId}-distribution-${index}`));
  const maximum = Math.max(...metrics.map((item) => Number(item.value)), 1);
  return <section className="finance-section distribution-panel" aria-labelledby="distribution-heading"><div className="section-heading"><div><p className="eyebrow">Range of outcomes</p><h2 id="distribution-heading">Conditional return distribution</h2></div><span>Scenario paths, not a forecast</span></div><div className="distribution-bars">{metrics.map((metric, index) => <div key={metric.metric_id}><span>{caseData.returnsDistribution.labels[index]}</span><div aria-hidden="true"><i style={{width: `${Math.max(4, Number(metric.value) / maximum * 100)}%`}} /></div><button type="button" onClick={(event) => openMetric({metric_id: metric.metric_id, label: `${caseData.returnsDistribution.labels[index]} gross multiple`, value: metric.display_value, detail: "Conditional seeded scenario output; not a forecast.", classification: metric.classification, lineage: metric.source_locator_ids, registry: metric}, event.currentTarget)}>{metric.display_value}</button></div>)}</div></section>;
}


/** Deterministic month-series line chart. Values are retained schedule outputs, never browser math. */
function MonthSeriesChart({series, months, breachMonths = [], label, formatValue}: {series: Array<{key: string; label: string; values: number[]; tone?: "accent" | "cash" | "breach"}>; months: number; breachMonths?: number[]; label: string; formatValue: (value: number) => string}) {
  const width = 760, height = 200, left = 64, right = 16, top = 12, bottom = 28;
  const maximum = Math.max(...series.flatMap((item) => item.values), 1);
  const x = (month: number) => left + (month - 1) / Math.max(1, months - 1) * (width - left - right);
  const y = (value: number) => top + (1 - Math.max(0, value) / maximum) * (height - top - bottom);
  const ticks = [0, .25, .5, .75, 1].map((ratio) => ratio * maximum);
  const tone = {accent: "var(--accent)", cash: "var(--positive)", breach: "var(--negative)"};
  return <figure className="chart-frame"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={label}>
    {ticks.map((tick) => <g key={tick}><line x1={left} x2={width - right} y1={y(tick)} y2={y(tick)} stroke="var(--line)" strokeWidth="1" /><text x={left - 8} y={y(tick) + 4} textAnchor="end" fontSize="12" fill="var(--muted)">{formatValue(tick)}</text></g>)}
    {breachMonths.map((month) => <rect key={month} x={x(month) - 2} y={top} width="4" height={height - top - bottom} fill="var(--negative-soft)" />)}
    {[1, 12, 24, 36, 48, 60].filter((month) => month <= months).map((month) => <text key={month} x={x(month)} y={height - 8} textAnchor="middle" fontSize="12" fill="var(--muted)">M{month}</text>)}
    {series.map((item) => <polyline key={item.key} fill="none" stroke={tone[item.tone ?? "accent"]} strokeWidth="1.75" strokeLinejoin="round" points={item.values.map((value, index) => `${x(index + 1)},${y(value)}`).join(" ")} />)}
    {breachMonths.slice(0, 1).map((month) => <text key={`label-${month}`} x={x(month) + 6} y={top + 10} fontSize="12" fill="var(--negative)">Covenant breach M{month}</text>)}
  </svg><figcaption className="chart-legend">{series.map((item) => <span key={item.key}><i data-tone={item.tone ?? "accent"} />{item.label}</span>)}{breachMonths.length ? <span><i data-tone="breach" />Modeled covenant breach</span> : null}</figcaption></figure>;
}

const creditLabel = (value: string) => ({HUMAN_JUDGMENT: "Analyst judgment", MIXED_CAUSAL_SYNTHETIC_AND_HUMAN_JUDGMENT: "Synthetic test + judgment", MIXED_CAUSAL_SYNTHETIC_AND_SCENARIO: "Synthetic test + scenario", DESCRIPTIVE_ZERO_BASE_CASE_CREDIT: "No base-case credit"}[value] ?? titleCaseIdentifier(value.toLowerCase()));

function PEValueBridge({caseData}: {caseData: CaseData}) {
  const bridge = caseData.valueCreationBridge;
  if (!bridge) return null;
  const levers = bridge.standalone.map((lever) => ({...lever, initiative: caseData.valueCreation.find((item) => item.initiative === lever.label)}));
  const maximum = Math.max(bridge.combined_exit_equity_cents, 1);
  const rows: Array<{key: string; label: string; note: string; start: number; end: number; delta: number | null; kind: "total" | "lever" | "residual"; xirr: string}> = [
    {key: "base", label: "Selected-case exit equity", note: "Retained base case", start: 0, end: bridge.base_exit_equity_cents, delta: null, kind: "total", xirr: percent(bridge.base_gross_xirr)},
  ];
  let running = bridge.base_exit_equity_cents;
  for (const lever of levers) {
    rows.push({key: lever.lever_id, label: lever.label, note: `${creditLabel(lever.credit_classification)} · ${money(lever.implementation_cost_cents)} to implement`, start: running, end: running + lever.exit_equity_delta_cents, delta: lever.exit_equity_delta_cents, kind: "lever", xirr: `+${percent(lever.gross_xirr_delta)}`});
    running += lever.exit_equity_delta_cents;
  }
  rows.push({key: "interaction", label: "Interaction between levers", note: "Combined rerun less the sum of standalone deltas", start: running, end: running + bridge.interaction_residual_cents, delta: bridge.interaction_residual_cents, kind: "residual", xirr: ""});
  rows.push({key: "combined", label: "All levers combined", note: "Illustrative and unverified; no lever is credited in the selected case", start: 0, end: bridge.combined_exit_equity_cents, delta: bridge.combined_exit_equity_delta_cents, kind: "total", xirr: percent(bridge.combined_gross_xirr)});
  return <section className="finance-section" aria-labelledby="value-bridge-heading"><div className="section-heading"><div><p className="eyebrow">Value creation bridge</p><h2 id="value-bridge-heading">What the plan could add to exit equity, and what it does not prove</h2></div><span>Retained deterministic reruns · not credited in the recommendation</span></div><p className="section-intro">Each lever is a retained full-model rerun. The credit classification says whether the lever rests on analyst judgment or a synthetic test; none of these deltas enters the selected-case return screen.</p><div className="value-bridge" role="group" aria-label="Exit equity value bridge">{rows.map((row) => <div key={row.key} className="value-bridge-row" data-kind={row.kind === "lever" ? undefined : row.kind}><span>{row.label}<small>{row.note}</small></span><span className="bar" aria-hidden="true"><i style={{left: `${Math.min(row.start, row.end) / maximum * 100}%`, width: `${Math.max(.4, Math.abs(row.end - row.start) / maximum * 100)}%`}} /></span><span className="num">{row.delta === null ? money(row.end) : `${row.delta >= 0 ? "+" : "−"}${money(Math.abs(row.delta))}`}{row.kind === "total" && row.delta !== null ? <small>{money(row.end)} total</small> : null}</span><span className="num"><small>{row.xirr ? `${row.xirr} return` : ""}</small></span></div>)}</div></section>;
}

function VCValueBridge({caseData}: {caseData: CaseData}) {
  const bridge = caseData.vcValueCreationBridge;
  if (!bridge) return null;
  const maximum = Math.max(bridge.combined_result_target_proceeds_cents, 1);
  const labelFor = (leverId: string) => caseData.valueCreation.find((item) => item.initiative.toLowerCase().includes(leverId.replaceAll("-", " ").split(" ")[0]))?.initiative ?? titleCaseIdentifier(leverId);
  let running = bridge.base_target_proceeds_cents;
  const rows = [{key: "base", label: "Milestone-case investor proceeds", note: "Retained base case", start: 0, end: bridge.base_target_proceeds_cents, delta: null as number | null, kind: "total" as const, xirr: percent(bridge.base_gross_xirr)}];
  for (const lever of bridge.standalone) {
    rows.push({key: lever.lever_id, label: labelFor(lever.lever_id), note: `${creditLabel(lever.credit_classification)} · ${money(lever.implementation_cost_cents)} to implement`, start: running, end: running + lever.target_proceeds_delta_cents, delta: lever.target_proceeds_delta_cents, kind: "lever" as never, xirr: lever.target_proceeds_delta_cents ? `+${percent(lever.gross_xirr_delta)}` : "no credit"});
    running += lever.target_proceeds_delta_cents;
  }
  rows.push({key: "interaction", label: "Interaction between levers", note: "Combined rerun less the sum of standalone deltas", start: running, end: running + bridge.interaction_residual_cents, delta: bridge.interaction_residual_cents, kind: "residual" as never, xirr: ""});
  rows.push({key: "combined", label: "All levers combined", note: "Illustrative and unverified; nothing here changes the HOLD posture", start: 0, end: bridge.combined_result_target_proceeds_cents, delta: bridge.combined_target_proceeds_delta_cents, kind: "total", xirr: percent(bridge.combined_result_gross_xirr)});
  return <section className="finance-section" aria-labelledby="value-bridge-heading"><div className="section-heading"><div><p className="eyebrow">Value creation bridge</p><h2 id="value-bridge-heading">What the plan could add to investor proceeds, and what it does not prove</h2></div><span>Retained deterministic reruns · not credited in the recommendation</span></div><div className="value-bridge" role="group" aria-label="Investor proceeds value bridge">{rows.map((row) => <div key={row.key} className="value-bridge-row" data-kind={row.kind === ("lever" as never) ? undefined : row.kind}><span>{row.label}<small>{row.note}</small></span><span className="bar" aria-hidden="true"><i style={{left: `${Math.min(row.start, row.end) / maximum * 100}%`, width: `${Math.max(.4, Math.abs(row.end - row.start) / maximum * 100)}%`}} /></span><span className="num">{row.delta === null ? money(row.end) : `${row.delta >= 0 ? "+" : "−"}${money(Math.abs(row.delta))}`}{row.kind === "total" && row.delta !== null ? <small>{money(row.end)} total</small> : null}</span><span className="num"><small>{row.xirr ? (row.xirr.startsWith("+") || /%$/.test(row.xirr) ? `${row.xirr} return` : row.xirr) : ""}</small></span></div>)}</div></section>;
}

function PEWorkspace({caseData, state, update, openMetric}: {caseData: CaseData; state: DealWorkspaceState; update: UpdateWorkspace; openMetric: OpenMetric}) {
  const engine = caseData.peEngine!;
  const scenarioKey = (["ask", "selected", "downside"] as const).includes(state.scenarioValues.peScenario as "ask" | "selected" | "downside") ? state.scenarioValues.peScenario as "ask" | "selected" | "downside" : "selected";
  const compareKey = (["ask", "selected", "downside"] as const).includes(state.scenarioValues.peCompare as "ask" | "selected" | "downside") ? state.scenarioValues.peCompare as "ask" | "selected" | "downside" : "downside";
  const scenario = engine[scenarioKey], comparison = engine[compareKey];
  const labels = {ask: "Seller ask", selected: "Canonical selected terms", downside: "Downside"};
  const axis = engine.sensitivities.axis_order.includes(state.scenarioValues.peAxis) ? state.scenarioValues.peAxis : engine.sensitivities.axis_order[0];
  const cells = engine.sensitivities.one_way.filter((item) => item.axis === axis);
  const selectedCell = cells.find((item) => item.cell_id === state.scenarioValues.peCell) ?? cells[Math.min(1, cells.length - 1)] ?? cells[0];
  const acceptedChange = state.changeControl?.dispositionEvents.at(-1)?.disposition === "ACCEPTED" ? state.changeControl : null;
  const acceptedRerun = acceptedChange ? engine.sensitivities.one_way.find((cell) => cell.result_receipt_sha256 === acceptedChange.deterministicReceiptSha256) : null;
  const revisedSelected = scenarioKey === "selected" ? acceptedRerun : null;
  const returnHurdle = Number((caseData.decision.metric_pairs ?? []).find((item) => item.metric_id === "atlasgrid-SELECTED-gross-irr")?.threshold_value ?? "0.22");
  const prefix = `${caseData.caseId}-${scenario.scenario_id}`;
  const exitCash = scenario.debt_schedule.months.at(-1)?.ending_cash_cents ?? 0;
  const axisLabels: Record<string, string> = {entry_enterprise_value_cents: "Entry enterprise value", full_cohort_nrr: "Full-cohort NRR", gross_margin: "Gross margin", annual_cash_rate: "Cash interest", funded_term_face_cents: "Funded debt", exit_multiple: "Exit multiple"};
  const cellMetric = (cell: PESensitivityCell, suffix: "irr" | "moic") => registryMetric(caseData, `${caseData.caseId}-${cell.cell_id}-${suffix}`, `Retained full-model sensitivity rerun for ${cell.assumption_label}.`);
  return <div className="finance-workspace">
    <section className="scenario-command"><div><p className="eyebrow">Working scenario</p><h2>Price, leverage and downside</h2><p>The canonical selected case remains unchanged. Tabs load retained full-model results; no return math is generated in the browser.</p></div><div className="scenario-controls"><div role="group" aria-label="PE scenario">{(["ask", "selected", "downside"] as const).map((key) => <button type="button" key={key} aria-pressed={scenarioKey === key} onClick={() => update({scenarioValues: {...state.scenarioValues, peScenario: key}})}>{labels[key]}</button>)}</div><label><span>Compare with</span><select value={compareKey} onChange={(event) => update({scenarioValues: {...state.scenarioValues, peCompare: event.target.value}})}>{(["ask", "selected", "downside"] as const).map((key) => <option key={key} value={key}>{labels[key]}</option>)}</select></label></div></section>
    <section className="decision-screen" aria-label="Buyout decision screen"><article><span>Current posture</span><strong>{acceptedRerun ? "REOPEN DILIGENCE" : "REPRICE"}</strong><small>{acceptedRerun ? "Accepted revised evidence moves selected terms below the screen" : "Seller terms miss the declared screen"}</small></article><article data-state={Number(engine.ask.gross_xirr) >= returnHurdle ? "clears" : "misses"}><span>Seller ask return</span><strong>{percent(engine.ask.gross_xirr)}</strong><small>Against {percent(returnHurdle)} hurdle</small></article><article data-state={Number(revisedSelected?.gross_xirr ?? engine.selected.gross_xirr) >= returnHurdle ? "clears" : "misses"}><span>{revisedSelected ? "Accepted V2 selected return" : "Selected-price return"}</span><strong>{percent(revisedSelected?.gross_xirr ?? engine.selected.gross_xirr)}</strong><small>{money(revisedSelected?.ending_debt_cents ?? engine.selected.debt_schedule.ending_debt_cents)} exit debt</small></article><article data-state={scenario.debt_schedule.first_covenant_breach_month ? "misses" : "clears"}><span>Selected covenant</span><strong>{scenario.debt_schedule.first_covenant_breach_month ? `Breach M${scenario.debt_schedule.first_covenant_breach_month}` : "No modeled breach"}</strong><small>{revisedSelected ? "Version 1 monthly schedule; V2 ending debt shown separately" : "Retained 60-month debt schedule"}</small></article></section>
    <section className="canonical-comparison" aria-label="Canonical and comparison cases"><article data-state={revisedSelected ? "what-if" : scenarioKey === "selected" ? "canonical" : "what-if"}><span>{revisedSelected ? "Accepted evidence revision" : scenarioKey === "selected" ? "Canonical case" : "Unapproved what-if"}</span><h3>{revisedSelected ? acceptedChange!.toVersion : labels[scenarioKey]}</h3><strong>{percent(revisedSelected?.gross_xirr ?? scenario.gross_xirr)} · {multiple(revisedSelected?.gross_moic ?? scenario.gross_moic)}</strong><small>{money(revisedSelected?.ending_debt_cents ?? scenario.debt_schedule.ending_debt_cents)} exit debt</small></article><article><span>Comparison</span><h3>{labels[compareKey]}</h3><strong>{percent(comparison.gross_xirr)} · {multiple(comparison.gross_moic)}</strong><small>{money(comparison.debt_schedule.ending_debt_cents)} exit debt</small></article></section>
    {revisedSelected ? <section className="finance-kpi-grid" aria-label="Accepted revised case return drivers"><article className="finance-kpi"><span>Annualized gross return</span><strong>{percent(revisedSelected.gross_xirr)}</strong><small>Accepted evidence-bound rerun</small></article><article className="finance-kpi"><span>Gross multiple</span><strong>{multiple(revisedSelected.gross_moic)}</strong><small>Accepted evidence-bound rerun</small></article><article className="finance-kpi"><span>Exit debt</span><strong>{money(revisedSelected.ending_debt_cents)}</strong><small>Accepted evidence-bound rerun</small></article><article className="finance-kpi"><span>Decision consequence</span><strong>Reopen diligence</strong><small>Selected return is below the working hurdle</small></article></section> : <section className="finance-kpi-grid" aria-label="Selected case return drivers"><MetricButton caseData={caseData} metricId={`${prefix}-gross-irr`} label="Annualized gross return" detail="Dated sponsor cash flows for the selected retained scenario." openMetric={openMetric} /><MetricButton caseData={caseData} metricId={`${prefix}-gross-moic`} label="Gross multiple" detail="Sponsor proceeds divided by dated invested capital." openMetric={openMetric} /><MetricButton caseData={caseData} metricId={`${prefix}-exit-debt`} label="Exit debt" detail="Month-60 term debt plus revolver from the exact cash schedule." openMetric={openMetric} /><MetricButton caseData={caseData} metricId={`${prefix}-min-liquidity`} label="Minimum liquidity" detail="Minimum ending cash across the retained 60-month schedule." openMetric={openMetric} /></section>}
    <section className="finance-section"><div className="section-heading"><div><p className="eyebrow">Debt schedule</p><h2>{revisedSelected ? "Version 1 monthly debt schedule" : "Cash-generated deleveraging"}</h2></div><span>{scenario.debt_schedule.first_covenant_breach_month ? `Covenant breach month ${scenario.debt_schedule.first_covenant_breach_month}` : "No modeled covenant breach"}</span></div>{revisedSelected ? <p className="revision-context">The accepted Version 2 rerun updates selected return and ending debt above. A revised month-by-month debt tape is not retained, so this chart remains explicitly Version 1.</p> : null}<p className="sr-only">Debt declines across the modeled sixty-month hold to {money(scenario.debt_schedule.ending_debt_cents)} at exit. {scenario.debt_schedule.first_covenant_breach_month ? `The first modeled covenant breach occurs in month ${scenario.debt_schedule.first_covenant_breach_month}.` : "No covenant breach is modeled."}</p><MonthSeriesChart label={`Monthly debt and cash for ${labels[scenarioKey]}`} months={scenario.debt_schedule.months.length} breachMonths={scenario.debt_schedule.months.filter((item) => item.covenant_breach).map((item) => item.month)} series={[{key: "debt", label: "Term debt + revolver", values: scenario.debt_schedule.months.map((item) => item.ending_term_cents + item.ending_revolver_cents)}, {key: "cash", label: "Ending cash", values: scenario.debt_schedule.months.map((item) => item.ending_cash_cents), tone: "cash"}]} formatValue={money} /><div className="bridge-equation" role="group" aria-label="Exit equity bridge"><div><small>Exit enterprise value</small><strong>{money(scenario.exit_enterprise_value_cents)}</strong></div><div><small>− Debt</small><strong>{money(scenario.debt_schedule.ending_debt_cents)}</strong></div><div><small>+ Exit cash</small><strong>{money(exitCash)}</strong></div><div><small>= Exit equity value</small><strong>{money(scenario.exit_equity_value_cents)}</strong></div></div></section>
    <section className="finance-section sensitivity-workspace"><div className="section-heading"><div><p className="eyebrow">Decision-change analysis</p><h2>One-way sensitivity</h2></div><span>Retained deterministic reruns</span></div><div className="sensitivity-controls"><label><span>Driver</span><select value={axis} onChange={(event) => {const nextAxis = event.target.value; const nextCells = engine.sensitivities.one_way.filter((item) => item.axis === nextAxis); update({scenarioValues: {...state.scenarioValues, peAxis: nextAxis, peCell: nextCells[Math.min(1, nextCells.length - 1)]?.cell_id ?? ""}});}}>{engine.sensitivities.axis_order.map((item) => <option key={item} value={item}>{axisLabels[item] ?? item}</option>)}</select></label><div role="group" aria-label="Sensitivity values">{cells.map((cell) => <button type="button" key={cell.cell_id} aria-pressed={selectedCell?.cell_id === cell.cell_id} onClick={() => update({scenarioValues: {...state.scenarioValues, peCell: cell.cell_id}})}>{cell.assumption_label}</button>)}</div></div>{selectedCell ? <div className="sensitivity-outcome"><button type="button" onClick={(event) => openMetric(cellMetric(selectedCell, "irr"), event.currentTarget)}><span>Annualized gross return</span><strong>{percent(selectedCell.gross_xirr)}</strong></button><button type="button" onClick={(event) => openMetric(cellMetric(selectedCell, "moic"), event.currentTarget)}><span>Gross multiple</span><strong>{multiple(selectedCell.gross_moic)}</strong></button><article><span>Exit debt</span><strong>{money(selectedCell.ending_debt_cents)}</strong></article><article><span>Covenant</span><strong>{selectedCell.first_covenant_breach_month ? `Breach M${selectedCell.first_covenant_breach_month}` : "No breach"}</strong></article></div> : null}<div className="heatmap-wrap"><table className="sensitivity-heatmap"><caption>Entry value × exit multiple · annualized gross return and gross multiple against the {percent(returnHurdle)} hurdle · the outlined cell is the selected structure</caption><thead><tr><th>Entry / exit</th><th>5.5x</th><th>6.5x</th><th>7.5x</th></tr></thead><tbody>{["$200M", "$210M", "$220M"].map((entry) => <tr key={entry}><th>{entry}</th>{["5.5x", "6.5x", "7.5x"].map((exit) => {const cell = engine.sensitivities.entry_exit_matrix.find((item) => item.assumption_label === `${entry} / ${exit}`); return <td key={exit} data-selected={entry === "$210M" && exit === "6.5x" || undefined} data-state={cell && Number(cell.gross_xirr) >= returnHurdle ? "clears" : "misses"}>{cell ? <button type="button" onClick={(event) => openMetric(cellMetric(cell, "irr"), event.currentTarget)}><strong>{percent(cell.gross_xirr)}</strong><small>{multiple(cell.gross_moic)}</small></button> : "—"}</td>;})}</tr>)}</tbody></table></div></section>
    <PEValueBridge caseData={caseData} />
    <ReturnDistribution caseData={caseData} openMetric={openMetric} />
  </div>;
}

function VCWorkspace({caseData, state, update, openMetric}: {caseData: CaseData; state: DealWorkspaceState; update: UpdateWorkspace; openMetric: OpenMetric}) {
  const engine = caseData.vcEngine!;
  const keys = ["base", "milestone", "downside", "financing_shortfall"] as const;
  const scenarioKey = keys.includes(state.scenarioValues.vcScenario as typeof keys[number]) ? state.scenarioValues.vcScenario as typeof keys[number] : "milestone";
  const compareKey = keys.includes(state.scenarioValues.vcCompare as typeof keys[number]) ? state.scenarioValues.vcCompare as typeof keys[number] : "downside";
  const result = engine[scenarioKey], comparison = engine[compareKey];
  const labels = {base: "Tranche withheld", milestone: "Milestone funded", downside: "Down round", financing_shortfall: "Financing shortfall"};
  const prefix = `helios-${result.scenario_id}`;
  const axis = engine.sensitivities.axis_order.includes(state.scenarioValues.vcAxis as VCSensitivityCell["axis"]) ? state.scenarioValues.vcAxis as VCSensitivityCell["axis"] : engine.sensitivities.default_axis;
  const cells = engine.sensitivities.cells.filter((item) => item.axis === axis);
  const selectedCell = cells.find((item) => item.cell_id === state.scenarioValues.vcCell) ?? cells.find((item) => item.is_baseline) ?? cells[0];
  const riskCell = engine.risk_sensitivity.cells.find((item) => item.cell_id === state.scenarioValues.vcRiskCell) ?? engine.risk_sensitivity.cells.find((item) => item.cell_id === engine.risk_sensitivity.canonical_cell_id)!;
  const policyThreshold = engine.risk_sensitivity.policy_threshold_choices.includes(state.scenarioValues.vcLossPolicy) ? state.scenarioValues.vcLossPolicy : engine.risk_sensitivity.canonical_policy_threshold;
  const lossScreenClears = Number(riskCell.catastrophe_probability) <= Number(policyThreshold);
  const axisLabel = engine.sensitivities.axis_definitions.find((item) => item.axis === axis)?.label ?? axis;
  const cellMetric = (cell: VCSensitivityCell, suffix: "gross-xirr" | "gross-moic") => registryMetric(caseData, `helios-${cell.cell_id}-${suffix}`, `Retained full-model sensitivity rerun for ${cell.assumption_label}.`);
  return <div className="finance-workspace">
    <section className="scenario-command"><div><p className="eyebrow">Working scenario</p><h2>Ownership, runway and preferences</h2><p>Scenario controls select retained financing ledgers. The canonical case and unreviewed policy remain unchanged.</p></div><div className="scenario-controls"><div role="group" aria-label="VC scenario">{keys.map((key) => <button type="button" key={key} aria-pressed={scenarioKey === key} onClick={() => update({scenarioValues: {...state.scenarioValues, vcScenario: key}})}>{labels[key]}</button>)}</div><label><span>Compare with</span><select value={compareKey} onChange={(event) => update({scenarioValues: {...state.scenarioValues, vcCompare: event.target.value}})}>{keys.map((key) => <option key={key} value={key}>{labels[key]}</option>)}</select></label></div></section>
    <section className="decision-screen" aria-label="Growth investment decision screen"><article><span>Current posture</span><strong>HOLD</strong><small>IC advancement is not authorized</small></article><article data-state={lossScreenClears ? "clears" : "misses"}><span>Assumed severe-loss probability</span><strong>{percent(riskCell.catastrophe_probability)}</strong><small>Analyst judgment · not a model estimate</small></article><article><span>Maximum acceptable loss probability</span><strong>{percent(policyThreshold)}</strong><small>Draft fund policy · not yet approved</small></article><article><span>Selected gross return</span><strong>{percent(result.gross_xirr)} · {multiple(result.gross_moic)}</strong><small>{lossScreenClears ? "Point return clears; policy ownership and open diligence still block advancement" : "Point return is not enough while the severe-loss assumption breaches the selected ceiling"}</small></article></section>
    <section className="canonical-comparison"><article data-state={scenarioKey === "milestone" ? "canonical" : "what-if"}><span>{scenarioKey === "milestone" ? "Canonical transaction case" : "Unapproved what-if"}</span><h3>{labels[scenarioKey]}</h3><strong>{percent(result.gross_xirr)} · {multiple(result.gross_moic)}</strong><small>{percent(result.target_ownership)} ownership</small></article><article><span>Comparison</span><h3>{labels[compareKey]}</h3><strong>{percent(comparison.gross_xirr)} · {multiple(comparison.gross_moic)}</strong><small>{money(comparison.minimum_cash_cents)} minimum cash</small></article></section>
    <section className="finance-kpi-grid"><MetricButton caseData={caseData} metricId={`${prefix}-gross-xirr`} label="Annualized gross return" detail="Dated gross return on funded Series C capital." openMetric={openMetric} /><MetricButton caseData={caseData} metricId={`${prefix}-gross-moic`} label="Gross multiple" detail="Exact waterfall proceeds divided by funded Series C cash." openMetric={openMetric} /><MetricButton caseData={caseData} metricId={`${prefix}-ownership`} label="Investor ownership" detail="Fully diluted ownership after funded events and option-pool refresh." openMetric={openMetric} /><MetricButton caseData={caseData} metricId={`${prefix}-minimum-cash`} label="Minimum cash" detail="Minimum ending cash across the signed monthly schedule." openMetric={openMetric} /></section>
    <section className="finance-section"><div className="section-heading"><div><p className="eyebrow">Runway</p><h2>Monthly cash and financing events</h2></div><span>{result.first_cash_exhaustion_month_without_contingent_financing ? `Shortfall month ${result.first_cash_exhaustion_month_without_contingent_financing}` : "Funded through exit"}</span></div><p className="sr-only">The scenario ends with {money(result.cash_by_month.at(-1)?.ending_cash_cents ?? 0)} of cash. {result.first_cash_exhaustion_month_without_contingent_financing ? `Without contingent financing, cash first exhausts in month ${result.first_cash_exhaustion_month_without_contingent_financing}.` : "The scenario remains funded through exit."}</p><MonthSeriesChart label={`Monthly ending cash for ${labels[scenarioKey]}`} months={result.cash_by_month.length} breachMonths={result.cash_by_month.filter((item) => item.first_exhaustion_without_contingent).map((item) => item.month)} series={[{key: "cash", label: "Ending cash", values: result.cash_by_month.map((item) => Math.max(0, item.ending_cash_cents)), tone: "cash"}]} formatValue={money} /><div className="financing-events">{result.financing_events.map((event) => <article key={event.event_id} data-state={event.status}><span>Month {event.actual_month}</span><strong>{event.event_type.replaceAll("_", " ").toLowerCase()}</strong><small>{money(event.new_money_cents)} · {event.status.toLowerCase()}</small></article>)}</div></section>
    <section className="finance-section split-finance"><div><div className="section-heading"><div><p className="eyebrow">Dilution</p><h2>Post-event cap table</h2></div></div><table><thead><tr><th>Holder</th><th>Class</th><th>Shares</th></tr></thead><tbody>{result.holders.map((holder) => <tr key={holder.holder_id}><th>{holderLabel(holder.holder_id)}</th><td>{classLabel(holder.class_id)}</td><td>{holder.shares.toLocaleString()}</td></tr>)}</tbody></table></div><div><div className="section-heading"><div><p className="eyebrow">Preference waterfall</p><h2>Exit proceeds by class</h2></div></div><table><thead><tr><th>Class</th><th>Election</th><th>Proceeds</th></tr></thead><tbody>{Object.entries(result.waterfall.class_proceeds_cents).map(([classId, proceeds]) => <tr key={classId}><th>{classLabel(classId)}</th><td>{result.waterfall.conversion_profile[classId] ? "Convert" : "Preference"}</td><td>{money(proceeds)}</td></tr>)}</tbody></table></div></section>
    <section className="finance-section sensitivity-workspace"><div className="section-heading"><div><p className="eyebrow">Decision-change analysis</p><h2>Operating sensitivity</h2></div><span>Retained deterministic reruns</span></div><div className="sensitivity-controls"><label><span>Driver</span><select value={axis} onChange={(event) => {const nextAxis = event.target.value as VCSensitivityCell["axis"]; const nextCell = engine.sensitivities.cells.find((item) => item.axis === nextAxis && item.is_baseline); update({scenarioValues: {...state.scenarioValues, vcAxis: nextAxis, vcCell: nextCell?.cell_id ?? ""}});}}>{engine.sensitivities.axis_definitions.map((item) => <option key={item.axis} value={item.axis}>{item.label}</option>)}</select></label><div role="group" aria-label={`${axisLabel} sensitivity values`}>{cells.map((cell) => <button type="button" key={cell.cell_id} aria-pressed={selectedCell.cell_id === cell.cell_id} onClick={() => update({scenarioValues: {...state.scenarioValues, vcCell: cell.cell_id}})}>{cell.assumption_label}</button>)}</div></div><div className="sensitivity-outcome"><button type="button" onClick={(event) => openMetric(cellMetric(selectedCell, "gross-xirr"), event.currentTarget)}><span>Annualized gross return</span><strong>{percent(selectedCell.gross_xirr)}</strong></button><button type="button" onClick={(event) => openMetric(cellMetric(selectedCell, "gross-moic"), event.currentTarget)}><span>Gross multiple</span><strong>{multiple(selectedCell.gross_moic)}</strong></button><article><span>Ownership</span><strong>{percent(selectedCell.target_ownership)}</strong></article><article><span>Decision consequence</span><strong>HOLD — loss screen evaluated separately</strong><small>{selectedCell.point_return_hurdle_status === "CLEARS" ? "Point-return hurdle clears" : "Point-return hurdle misses"} · this operating cell does not rerun the loss distribution</small></article></div></section>
    <section className="finance-section risk-lab">
      <div className="section-heading"><div><p className="eyebrow">Loss risk and fund policy</p><h2>What must be true to avoid a capital-loss outcome?</h2></div><span>{lossScreenClears ? "Selected screen clears" : "Selected screen misses"}</span></div>
      <p>The working case assumes a {percent(riskCell.catastrophe_probability)} chance of a severe outcome where the investment returns less than 1.0x, against a selected maximum of {percent(policyThreshold)}. This is analyst judgment, not a forecast. The decision remains HOLD until the assumption, policy, and open diligence receive human review.</p>
      <div className="risk-controls"><label><span>Assumed severe-loss probability</span><select value={riskCell.cell_id} onChange={(event) => update({scenarioValues: {...state.scenarioValues, vcRiskCell: event.target.value}})}>{engine.risk_sensitivity.cells.map((cell) => <option key={cell.cell_id} value={cell.cell_id}>{cell.profile_label} · {percent(cell.catastrophe_probability)} severe-loss assumption</option>)}</select></label><label><span>Maximum acceptable loss probability</span><select value={policyThreshold} onChange={(event) => update({scenarioValues: {...state.scenarioValues, vcLossPolicy: event.target.value}})}>{engine.risk_sensitivity.policy_threshold_choices.map((value) => <option key={value} value={value}>{percent(value)}</option>)}</select></label></div>
      <div className="risk-result">
        <article><span>Assumed severe-loss probability</span><strong>{percent(riskCell.catastrophe_probability)}</strong><small>Analyst input · unreviewed</small></article>
        <article><span>Selected policy test</span><strong data-state={lossScreenClears ? "clears" : "misses"}>{lossScreenClears ? "Within limit" : "Above limit"}</strong><small>Against {percent(policyThreshold)} maximum</small></article>
        <article><span>Illustrative replay result</span><strong>{percent(riskCell.probability_below_one)}</strong><small>Checks the synthetic scenario mechanics only</small></article>
        <article><span>Decision</span><strong>HOLD</strong><small>Policy unreviewed · open diligence · IC decision pending</small></article>
      </div>
      <details><summary>Method, ownership, and replay detail</summary><dl><div><dt>Desk policy owner</dt><dd>{engine.desk_policy.owner} · {engine.desk_policy.status.toLowerCase()}</dd></div><div><dt>Package hurdle author</dt><dd>{engine.risk_policy.owner} · representation only</dd></div><div><dt>Severe-loss prior owner</dt><dd>{engine.distribution.priors.owner} · {engine.distribution.priors.approval_status.toLowerCase()}</dd></div><div><dt>Canonical loss ceiling</dt><dd>{percent(engine.risk_sensitivity.canonical_policy_threshold)}</dd></div><div><dt>Seeded replay check</dt><dd>{riskCell.draws.toLocaleString()} paths; {riskCell.loss_decomposition.catastrophe_loss_paths}/{riskCell.loss_decomposition.catastrophe_paths} severe-state paths lose and {riskCell.loss_decomposition.continuous_loss_paths}/{riskCell.loss_decomposition.continuous_paths} continuous paths lose</dd></div><div><dt>Current profile</dt><dd>{riskCell.profile_rationale}</dd></div></dl></details>
    </section>
    <VCValueBridge caseData={caseData} />
    <ReturnDistribution caseData={caseData} openMetric={openMetric} />
  </div>;
}

export function FinancialWorkspace({caseData, state, update, openMetric}: {caseData: CaseData; state: DealWorkspaceState; update: UpdateWorkspace; openMetric: OpenMetric}) {
  return caseData.peEngine ? <PEWorkspace caseData={caseData} state={state} update={update} openMetric={openMetric} /> : caseData.vcEngine ? <VCWorkspace caseData={caseData} state={state} update={update} openMetric={openMetric} /> : null;
}
