import {registeredMetric} from "./data-contract";
import type {CaseData, Metric, PECaseResult, PESensitivityCell, VCSensitivityCell, VCScenarioResult} from "./types";
import type {DealWorkspaceState} from "./workspace-state";

type OpenMetric = (metric: Metric, trigger: HTMLElement) => void;
type UpdateWorkspace = (patch: Partial<DealWorkspaceState>) => void;

const money = (cents: number) => new Intl.NumberFormat("en-US", {style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 1}).format(cents / 100);
const percent = (value: string | number) => `${(Number(value) * 100).toFixed(1)}%`;
const multiple = (value: string | number) => `${Number(value).toFixed(2)}x`;

export interface ScenarioMemoSummary {state: "Canonical case" | "Unapproved what-if"; label: string; returnLine: string; detail: string}

export function scenarioMemoSummary(caseData: CaseData, state: DealWorkspaceState): ScenarioMemoSummary {
  if (caseData.peEngine) {
    const key = (["ask", "selected", "downside"] as const).includes(state.scenarioValues.peScenario as "ask" | "selected" | "downside") ? state.scenarioValues.peScenario as "ask" | "selected" | "downside" : "selected";
    const labels = {ask: "Seller ask", selected: "Selected terms", downside: "Downside"};
    const result = caseData.peEngine[key];
    return {state: key === "selected" ? "Canonical case" : "Unapproved what-if", label: labels[key], returnLine: `${percent(result.gross_xirr)} annualized gross return · ${multiple(result.gross_moic)} gross multiple`, detail: `${money(result.debt_schedule.ending_debt_cents)} exit debt. This selected working scenario does not overwrite the canonical case.`};
  }
  const keys = ["base", "milestone", "downside", "financing_shortfall"] as const;
  const key = keys.includes(state.scenarioValues.vcScenario as typeof keys[number]) ? state.scenarioValues.vcScenario as typeof keys[number] : "milestone";
  const labels = {base: "Tranche withheld", milestone: "Milestone funded", downside: "Down round", financing_shortfall: "Financing shortfall"};
  const result = caseData.vcEngine![key];
  const engine = caseData.vcEngine!;
  const riskCell = engine.risk_sensitivity.cells.find((item) => item.cell_id === state.scenarioValues.vcRiskCell) ?? engine.risk_sensitivity.cells.find((item) => item.cell_id === engine.risk_sensitivity.canonical_cell_id)!;
  const policyThreshold = engine.risk_sensitivity.policy_threshold_choices.includes(state.scenarioValues.vcLossPolicy) ? state.scenarioValues.vcLossPolicy : engine.risk_sensitivity.canonical_policy_threshold;
  const isCanonical = key === "milestone" && riskCell.cell_id === engine.risk_sensitivity.canonical_cell_id && policyThreshold === engine.risk_sensitivity.canonical_policy_threshold;
  const policyResult = Number(riskCell.probability_below_one) <= Number(policyThreshold) ? "clears" : "misses";
  return {state: isCanonical ? "Canonical case" : "Unapproved what-if", label: labels[key], returnLine: `${percent(result.gross_xirr)} annualized gross return · ${multiple(result.gross_moic)} gross multiple`, detail: `${percent(result.target_ownership)} investor ownership · ${money(result.minimum_cash_cents)} minimum cash · the selected analyst prior implies a ${percent(riskCell.probability_below_one)} chance of returning less than 1.0x, which ${policyResult} the selected ${percent(policyThreshold)} ceiling. This working case does not overwrite the canonical transaction or policy case.`};
}

function registryMetric(caseData: CaseData, metricId: string, detail: string, label?: string): Metric {
  const registry = registeredMetric(caseData, metricId);
  return {metric_id: metricId, label: label ?? registry.label, value: registry.display_value, detail, classification: registry.classification, lineage: registry.source_locator_ids, registry};
}

function MetricButton({caseData, metricId, detail, label, openMetric}: {caseData: CaseData; metricId: string; detail: string; label?: string; openMetric: OpenMetric}) {
  const metric = registryMetric(caseData, metricId, detail, label);
  return <button type="button" className="finance-kpi" data-metric-id={metricId} onClick={(event) => openMetric(metric, event.currentTarget)}><span>{metric.label}</span><strong>{metric.value}</strong><small>View source</small></button>;
}

function ReturnDistribution({caseData, openMetric}: {caseData: CaseData; openMetric: OpenMetric}) {
  const metrics = caseData.returnsDistribution.moic.map((_, index) => registeredMetric(caseData, caseData.caseId === "helios" ? `helios-distribution-moic-${index}` : `${caseData.caseId}-distribution-${index}`));
  const maximum = Math.max(...metrics.map((item) => Number(item.value)), 1);
  return <section className="finance-section distribution-panel" aria-labelledby="distribution-heading"><div className="section-heading"><div><p className="eyebrow">Range of outcomes</p><h2 id="distribution-heading">Conditional return distribution</h2></div><span>Scenario paths, not a forecast</span></div><div className="distribution-bars">{metrics.map((metric, index) => <div key={metric.metric_id}><span>{caseData.returnsDistribution.labels[index]}</span><div aria-hidden="true"><i style={{width: `${Math.max(4, Number(metric.value) / maximum * 100)}%`}} /></div><button type="button" onClick={(event) => openMetric({metric_id: metric.metric_id, label: `${caseData.returnsDistribution.labels[index]} gross multiple`, value: metric.display_value, detail: "Conditional seeded scenario output; not a forecast.", classification: metric.classification, lineage: metric.source_locator_ids, registry: metric}, event.currentTarget)}>{metric.display_value}</button></div>)}</div></section>;
}

function PEWorkspace({caseData, state, update, openMetric}: {caseData: CaseData; state: DealWorkspaceState; update: UpdateWorkspace; openMetric: OpenMetric}) {
  const engine = caseData.peEngine!;
  const scenarioKey = (["ask", "selected", "downside"] as const).includes(state.scenarioValues.peScenario as "ask" | "selected" | "downside") ? state.scenarioValues.peScenario as "ask" | "selected" | "downside" : "selected";
  const compareKey = (["ask", "selected", "downside"] as const).includes(state.scenarioValues.peCompare as "ask" | "selected" | "downside") ? state.scenarioValues.peCompare as "ask" | "selected" | "downside" : "downside";
  const scenario = engine[scenarioKey], comparison = engine[compareKey];
  const labels = {ask: "Seller ask", selected: "Canonical selected terms", downside: "Downside"};
  const axis = engine.sensitivities.axis_order.includes(state.scenarioValues.peAxis) ? state.scenarioValues.peAxis : engine.sensitivities.axis_order[0];
  const cells = engine.sensitivities.one_way.filter((item) => item.axis === axis);
  const selectedCell = cells.find((item) => item.cell_id === state.scenarioValues.peCell) ?? cells[Math.min(1, cells.length - 1)] ?? cells[0];
  const returnHurdle = Number((caseData.decision.metric_pairs ?? []).find((item) => item.metric_id === "atlasgrid-SELECTED-gross-irr")?.threshold_value ?? "0.22");
  const prefix = `${caseData.caseId}-${scenario.scenario_id}`;
  const maximumDebt = Math.max(...scenario.debt_schedule.months.map((item) => item.ending_term_cents + item.ending_revolver_cents), 1);
  const axisLabels: Record<string, string> = {entry_enterprise_value_cents: "Entry enterprise value", full_cohort_nrr: "Full-cohort NRR", gross_margin: "Gross margin", annual_cash_rate: "Cash interest", funded_term_face_cents: "Funded debt", exit_multiple: "Exit multiple"};
  const cellMetric = (cell: PESensitivityCell, suffix: "irr" | "moic") => registryMetric(caseData, `${caseData.caseId}-${cell.cell_id}-${suffix}`, `Retained full-model sensitivity rerun for ${cell.assumption_label}.`);
  return <div className="finance-workspace">
    <section className="scenario-command"><div><p className="eyebrow">Working scenario</p><h2>Price, leverage and downside</h2><p>The canonical selected case remains unchanged. Tabs load retained full-model results; no return math is generated in the browser.</p></div><div className="scenario-controls"><div role="group" aria-label="PE scenario">{(["ask", "selected", "downside"] as const).map((key) => <button type="button" key={key} aria-pressed={scenarioKey === key} onClick={() => update({scenarioValues: {...state.scenarioValues, peScenario: key}})}>{labels[key]}</button>)}</div><label><span>Compare with</span><select value={compareKey} onChange={(event) => update({scenarioValues: {...state.scenarioValues, peCompare: event.target.value}})}>{(["ask", "selected", "downside"] as const).map((key) => <option key={key} value={key}>{labels[key]}</option>)}</select></label></div></section>
    <section className="decision-screen" aria-label="Buyout decision screen"><article><span>Current posture</span><strong>REPRICE</strong><small>Seller terms miss the declared screen</small></article><article data-state={Number(engine.ask.gross_xirr) >= returnHurdle ? "clears" : "misses"}><span>Seller ask return</span><strong>{percent(engine.ask.gross_xirr)}</strong><small>Against {percent(returnHurdle)} hurdle</small></article><article data-state={Number(engine.selected.gross_xirr) >= returnHurdle ? "clears" : "misses"}><span>Selected-price return</span><strong>{percent(engine.selected.gross_xirr)}</strong><small>{money(engine.selected.debt_schedule.ending_debt_cents)} exit debt</small></article><article data-state={scenario.debt_schedule.first_covenant_breach_month ? "misses" : "clears"}><span>Selected covenant</span><strong>{scenario.debt_schedule.first_covenant_breach_month ? `Breach M${scenario.debt_schedule.first_covenant_breach_month}` : "No modeled breach"}</strong><small>Retained 60-month debt schedule</small></article></section>
    <section className="canonical-comparison" aria-label="Canonical and comparison cases"><article data-state={scenarioKey === "selected" ? "canonical" : "what-if"}><span>{scenarioKey === "selected" ? "Canonical case" : "Unapproved what-if"}</span><h3>{labels[scenarioKey]}</h3><strong>{percent(scenario.gross_xirr)} · {multiple(scenario.gross_moic)}</strong><small>{money(scenario.debt_schedule.ending_debt_cents)} exit debt</small></article><article><span>Comparison</span><h3>{labels[compareKey]}</h3><strong>{percent(comparison.gross_xirr)} · {multiple(comparison.gross_moic)}</strong><small>{money(comparison.debt_schedule.ending_debt_cents)} exit debt</small></article></section>
    <section className="finance-kpi-grid" aria-label="Selected case return drivers"><MetricButton caseData={caseData} metricId={`${prefix}-gross-irr`} label="Annualized gross return" detail="Dated sponsor cash flows for the selected retained scenario." openMetric={openMetric} /><MetricButton caseData={caseData} metricId={`${prefix}-gross-moic`} label="Gross multiple" detail="Sponsor proceeds divided by dated invested capital." openMetric={openMetric} /><MetricButton caseData={caseData} metricId={`${prefix}-exit-debt`} label="Exit debt" detail="Month-60 term debt plus revolver from the exact cash schedule." openMetric={openMetric} /><MetricButton caseData={caseData} metricId={`${prefix}-min-liquidity`} label="Minimum liquidity" detail="Minimum ending cash across the retained 60-month schedule." openMetric={openMetric} /></section>
    <section className="finance-section"><div className="section-heading"><div><p className="eyebrow">Debt schedule</p><h2>Cash-generated deleveraging</h2></div><span>{scenario.debt_schedule.first_covenant_breach_month ? `Covenant breach month ${scenario.debt_schedule.first_covenant_breach_month}` : "No modeled covenant breach"}</span></div><p className="sr-only">Debt declines across the modeled sixty-month hold to {money(scenario.debt_schedule.ending_debt_cents)} at exit. {scenario.debt_schedule.first_covenant_breach_month ? `The first modeled covenant breach occurs in month ${scenario.debt_schedule.first_covenant_breach_month}.` : "No covenant breach is modeled."}</p><div className="tape-chart" aria-hidden="true">{scenario.debt_schedule.months.map((item) => <i key={item.month} className={item.covenant_breach ? "breach" : ""} style={{height: `${Math.max(3, (item.ending_term_cents + item.ending_revolver_cents) / maximumDebt * 100)}%`}} title={`Month ${item.month}: ${money(item.ending_term_cents + item.ending_revolver_cents)}`} />)}</div><div className="bridge-equation"><span><small>Exit enterprise value</small><strong>{money(scenario.exit_enterprise_value_cents)}</strong></span><b>−</b><span><small>Debt</small><strong>{money(scenario.debt_schedule.ending_debt_cents)}</strong></span><b>=</b><span><small>Exit equity value</small><strong>{money(scenario.exit_equity_value_cents)}</strong></span></div></section>
    <section className="finance-section sensitivity-workspace"><div className="section-heading"><div><p className="eyebrow">Decision-change analysis</p><h2>One-way sensitivity</h2></div><span>Retained deterministic reruns</span></div><div className="sensitivity-controls"><label><span>Driver</span><select value={axis} onChange={(event) => {const nextAxis = event.target.value; const nextCells = engine.sensitivities.one_way.filter((item) => item.axis === nextAxis); update({scenarioValues: {...state.scenarioValues, peAxis: nextAxis, peCell: nextCells[Math.min(1, nextCells.length - 1)]?.cell_id ?? ""}});}}>{engine.sensitivities.axis_order.map((item) => <option key={item} value={item}>{axisLabels[item] ?? item}</option>)}</select></label><div role="group" aria-label="Sensitivity values">{cells.map((cell) => <button type="button" key={cell.cell_id} aria-pressed={selectedCell?.cell_id === cell.cell_id} onClick={() => update({scenarioValues: {...state.scenarioValues, peCell: cell.cell_id}})}>{cell.assumption_label}</button>)}</div></div>{selectedCell ? <div className="sensitivity-outcome"><button type="button" onClick={(event) => openMetric(cellMetric(selectedCell, "irr"), event.currentTarget)}><span>Annualized gross return</span><strong>{percent(selectedCell.gross_xirr)}</strong></button><button type="button" onClick={(event) => openMetric(cellMetric(selectedCell, "moic"), event.currentTarget)}><span>Gross multiple</span><strong>{multiple(selectedCell.gross_moic)}</strong></button><article><span>Exit debt</span><strong>{money(selectedCell.ending_debt_cents)}</strong></article><article><span>Covenant</span><strong>{selectedCell.first_covenant_breach_month ? `Breach M${selectedCell.first_covenant_breach_month}` : "No breach"}</strong></article></div> : null}<div className="heatmap-wrap"><table className="sensitivity-heatmap"><caption>Entry value × exit multiple · {percent(returnHurdle)} gross return hurdle</caption><thead><tr><th>Entry / exit</th><th>5.5x</th><th>6.5x</th><th>7.5x</th></tr></thead><tbody>{["$200M", "$210M", "$220M"].map((entry) => <tr key={entry}><th>{entry}</th>{["5.5x", "6.5x", "7.5x"].map((exit) => {const cell = engine.sensitivities.entry_exit_matrix.find((item) => item.assumption_label === `${entry} / ${exit}`); return <td key={exit} data-state={cell && Number(cell.gross_xirr) >= returnHurdle ? "clears" : "misses"}>{cell ? <button type="button" onClick={(event) => openMetric(cellMetric(cell, "irr"), event.currentTarget)}><strong>{percent(cell.gross_xirr)}</strong><small>{multiple(cell.gross_moic)}</small></button> : "—"}</td>;})}</tr>)}</tbody></table></div></section>
    <ReturnDistribution caseData={caseData} openMetric={openMetric} />
  </div>;
}

function VCWorkspace({caseData, state, update, openMetric}: {caseData: CaseData; state: DealWorkspaceState; update: UpdateWorkspace; openMetric: OpenMetric}) {
  const engine = caseData.vcEngine!;
  const keys = ["base", "milestone", "downside", "financing_shortfall"] as const;
  const scenarioKey = keys.includes(state.scenarioValues.vcScenario as typeof keys[number]) ? state.scenarioValues.vcScenario as typeof keys[number] : "milestone";
  const compareKey = keys.includes(state.scenarioValues.vcCompare as typeof keys[number]) ? state.scenarioValues.vcCompare as typeof keys[number] : "downside";
  const result = engine[scenarioKey], comparison = engine[compareKey];
  const labels = {base: "Tranche withheld", milestone: "Milestone funded", downside: "Down round", financing_shortfall: "Financing shortfall"};
  const prefix = `helios-${result.scenario_id}`;
  const axis = engine.sensitivities.axis_order.includes(state.scenarioValues.vcAxis as VCSensitivityCell["axis"]) ? state.scenarioValues.vcAxis as VCSensitivityCell["axis"] : engine.sensitivities.default_axis;
  const cells = engine.sensitivities.cells.filter((item) => item.axis === axis);
  const selectedCell = cells.find((item) => item.cell_id === state.scenarioValues.vcCell) ?? cells.find((item) => item.is_baseline) ?? cells[0];
  const riskCell = engine.risk_sensitivity.cells.find((item) => item.cell_id === state.scenarioValues.vcRiskCell) ?? engine.risk_sensitivity.cells.find((item) => item.cell_id === engine.risk_sensitivity.canonical_cell_id)!;
  const policyThreshold = engine.risk_sensitivity.policy_threshold_choices.includes(state.scenarioValues.vcLossPolicy) ? state.scenarioValues.vcLossPolicy : engine.risk_sensitivity.canonical_policy_threshold;
  const maximumCash = Math.max(...result.cash_by_month.map((item) => item.ending_cash_cents), 1);
  const axisLabel = engine.sensitivities.axis_definitions.find((item) => item.axis === axis)?.label ?? axis;
  const cellMetric = (cell: VCSensitivityCell, suffix: "gross-xirr" | "gross-moic") => registryMetric(caseData, `helios-${cell.cell_id}-${suffix}`, `Retained full-model sensitivity rerun for ${cell.assumption_label}.`);
  return <div className="finance-workspace">
    <section className="scenario-command"><div><p className="eyebrow">Working scenario</p><h2>Ownership, runway and preferences</h2><p>Scenario controls select retained financing ledgers. The canonical case and unreviewed policy remain unchanged.</p></div><div className="scenario-controls"><div role="group" aria-label="VC scenario">{keys.map((key) => <button type="button" key={key} aria-pressed={scenarioKey === key} onClick={() => update({scenarioValues: {...state.scenarioValues, vcScenario: key}})}>{labels[key]}</button>)}</div><label><span>Compare with</span><select value={compareKey} onChange={(event) => update({scenarioValues: {...state.scenarioValues, vcCompare: event.target.value}})}>{keys.map((key) => <option key={key} value={key}>{labels[key]}</option>)}</select></label></div></section>
    <section className="decision-screen" aria-label="Growth investment decision screen"><article><span>Current posture</span><strong>HOLD</strong><small>IC advancement is not authorized</small></article><article data-state={Number(riskCell.probability_below_one) <= Number(policyThreshold) ? "clears" : "misses"}><span>Prior-implied loss frequency</span><strong>{percent(riskCell.probability_below_one)}</strong><small>Selected analyst prior · not an empirical forecast</small></article><article><span>Desk policy maximum</span><strong>{percent(policyThreshold)}</strong><small>Draft and unreviewed</small></article><article><span>Selected gross return</span><strong>{percent(result.gross_xirr)} · {multiple(result.gross_moic)}</strong><small>Attractive point return does not clear the binding loss screen</small></article></section>
    <section className="canonical-comparison"><article data-state={scenarioKey === "milestone" ? "canonical" : "what-if"}><span>{scenarioKey === "milestone" ? "Canonical transaction case" : "Unapproved what-if"}</span><h3>{labels[scenarioKey]}</h3><strong>{percent(result.gross_xirr)} · {multiple(result.gross_moic)}</strong><small>{percent(result.target_ownership)} ownership</small></article><article><span>Comparison</span><h3>{labels[compareKey]}</h3><strong>{percent(comparison.gross_xirr)} · {multiple(comparison.gross_moic)}</strong><small>{money(comparison.minimum_cash_cents)} minimum cash</small></article></section>
    <section className="finance-kpi-grid"><MetricButton caseData={caseData} metricId={`${prefix}-gross-xirr`} label="Annualized gross return" detail="Dated gross return on funded Series C capital." openMetric={openMetric} /><MetricButton caseData={caseData} metricId={`${prefix}-gross-moic`} label="Gross multiple" detail="Exact waterfall proceeds divided by funded Series C cash." openMetric={openMetric} /><MetricButton caseData={caseData} metricId={`${prefix}-ownership`} label="Investor ownership" detail="Fully diluted ownership after funded events and option-pool refresh." openMetric={openMetric} /><MetricButton caseData={caseData} metricId={`${prefix}-minimum-cash`} label="Minimum cash" detail="Minimum ending cash across the signed monthly schedule." openMetric={openMetric} /></section>
    <section className="finance-section"><div className="section-heading"><div><p className="eyebrow">Runway</p><h2>Monthly cash and financing events</h2></div><span>{result.first_cash_exhaustion_month_without_contingent_financing ? `Shortfall month ${result.first_cash_exhaustion_month_without_contingent_financing}` : "Funded through exit"}</span></div><p className="sr-only">The scenario ends with {money(result.cash_by_month.at(-1)?.ending_cash_cents ?? 0)} of cash. {result.first_cash_exhaustion_month_without_contingent_financing ? `Without contingent financing, cash first exhausts in month ${result.first_cash_exhaustion_month_without_contingent_financing}.` : "The scenario remains funded through exit."}</p><div className="tape-chart cash-chart" aria-hidden="true">{result.cash_by_month.map((item) => <i key={item.month} className={item.first_exhaustion_without_contingent ? "breach" : ""} style={{height: `${Math.max(3, Math.max(0, item.ending_cash_cents) / maximumCash * 100)}%`}} title={`Month ${item.month}: ${money(item.ending_cash_cents)}`} />)}</div><div className="financing-events">{result.financing_events.map((event) => <article key={event.event_id} data-state={event.status}><span>Month {event.actual_month}</span><strong>{event.event_type.replaceAll("_", " ").toLowerCase()}</strong><small>{money(event.new_money_cents)} · {event.status.toLowerCase()}</small></article>)}</div></section>
    <section className="finance-section split-finance"><div><div className="section-heading"><div><p className="eyebrow">Dilution</p><h2>Post-event cap table</h2></div></div><table><thead><tr><th>Holder</th><th>Class</th><th>Shares</th></tr></thead><tbody>{result.holders.map((holder) => <tr key={holder.holder_id}><th>{holder.holder_id}</th><td>{holder.class_id}</td><td>{holder.shares.toLocaleString()}</td></tr>)}</tbody></table></div><div><div className="section-heading"><div><p className="eyebrow">Preference waterfall</p><h2>Exit proceeds by class</h2></div></div><table><thead><tr><th>Class</th><th>Election</th><th>Proceeds</th></tr></thead><tbody>{Object.entries(result.waterfall.class_proceeds_cents).map(([classId, proceeds]) => <tr key={classId}><th>{classId}</th><td>{result.waterfall.conversion_profile[classId] ? "Convert" : "Preference"}</td><td>{money(proceeds)}</td></tr>)}</tbody></table></div></section>
    <section className="finance-section sensitivity-workspace"><div className="section-heading"><div><p className="eyebrow">Decision-change analysis</p><h2>Operating sensitivity</h2></div><span>Retained deterministic reruns</span></div><div className="sensitivity-controls"><label><span>Driver</span><select value={axis} onChange={(event) => {const nextAxis = event.target.value as VCSensitivityCell["axis"]; const nextCell = engine.sensitivities.cells.find((item) => item.axis === nextAxis && item.is_baseline); update({scenarioValues: {...state.scenarioValues, vcAxis: nextAxis, vcCell: nextCell?.cell_id ?? ""}});}}>{engine.sensitivities.axis_definitions.map((item) => <option key={item.axis} value={item.axis}>{item.label}</option>)}</select></label><div role="group" aria-label={`${axisLabel} sensitivity values`}>{cells.map((cell) => <button type="button" key={cell.cell_id} aria-pressed={selectedCell.cell_id === cell.cell_id} onClick={() => update({scenarioValues: {...state.scenarioValues, vcCell: cell.cell_id}})}>{cell.assumption_label}</button>)}</div></div><div className="sensitivity-outcome"><button type="button" onClick={(event) => openMetric(cellMetric(selectedCell, "gross-xirr"), event.currentTarget)}><span>Annualized gross return</span><strong>{percent(selectedCell.gross_xirr)}</strong></button><button type="button" onClick={(event) => openMetric(cellMetric(selectedCell, "gross-moic"), event.currentTarget)}><span>Gross multiple</span><strong>{multiple(selectedCell.gross_moic)}</strong></button><article><span>Ownership</span><strong>{percent(selectedCell.target_ownership)}</strong></article><article><span>Decision consequence</span><strong>HOLD — loss screen evaluated separately</strong><small>{selectedCell.point_return_hurdle_status === "CLEARS" ? "Point-return hurdle clears" : "Point-return hurdle misses"} · this operating cell does not rerun the loss distribution</small></article></div></section>
    <section className="finance-section risk-lab"><div className="section-heading"><div><p className="eyebrow">Risk assumptions and policy</p><h2>Loss-frequency working case</h2></div><span>Canonical case preserved</span></div><p>This is a sensitivity to an unreviewed analyst catastrophe prior—not an observed loss rate or an empirical forecast. The ceiling is a separate Desk-owned draft policy; package-requested hurdles do not grade the case.</p><div className="risk-controls"><label><span>Analyst scenario prior</span><select value={riskCell.cell_id} onChange={(event) => update({scenarioValues: {...state.scenarioValues, vcRiskCell: event.target.value}})}>{engine.risk_sensitivity.cells.map((cell) => <option key={cell.cell_id} value={cell.cell_id}>{cell.profile_label} · {percent(cell.catastrophe_probability)} catastrophe prior</option>)}</select></label><label><span>Maximum probability below 1.0x</span><select value={policyThreshold} onChange={(event) => update({scenarioValues: {...state.scenarioValues, vcLossPolicy: event.target.value}})}>{engine.risk_sensitivity.policy_threshold_choices.map((value) => <option key={value} value={value}>{percent(value)}</option>)}</select></label></div><div className="risk-result"><article><span>Prior-implied loss frequency</span><strong>{percent(riskCell.probability_below_one)}</strong><small>{riskCell.draws.toLocaleString()} seeded synthetic paths · not a forecast</small></article><article><span>Selected policy test</span><strong data-state={Number(riskCell.probability_below_one) <= Number(policyThreshold) ? "clears" : "misses"}>{Number(riskCell.probability_below_one) <= Number(policyThreshold) ? "Clears" : "Misses"}</strong><small>Against {percent(policyThreshold)} maximum</small></article><article><span>Decision</span><strong>HOLD</strong><small>Policy unreviewed · open diligence · IC decision pending</small></article></div><details><summary>Ownership and assumptions</summary><dl><div><dt>Desk policy owner</dt><dd>{engine.desk_policy.owner} · {engine.desk_policy.status.toLowerCase()}</dd></div><div><dt>Package hurdle author</dt><dd>{engine.risk_policy.owner} · representation only</dd></div><div><dt>Simulation owner</dt><dd>{engine.distribution.priors.owner} · {engine.distribution.priors.approval_status.toLowerCase()}</dd></div><div><dt>Canonical loss ceiling</dt><dd>{percent(engine.risk_sensitivity.canonical_policy_threshold)}</dd></div><div><dt>Current profile</dt><dd>{riskCell.profile_rationale}</dd></div></dl></details></section>
    <ReturnDistribution caseData={caseData} openMetric={openMetric} />
  </div>;
}

export function FinancialWorkspace({caseData, state, update, openMetric}: {caseData: CaseData; state: DealWorkspaceState; update: UpdateWorkspace; openMetric: OpenMetric}) {
  return caseData.peEngine ? <PEWorkspace caseData={caseData} state={state} update={update} openMetric={openMetric} /> : caseData.vcEngine ? <VCWorkspace caseData={caseData} state={state} update={update} openMetric={openMetric} /> : null;
}
