import {act, renderHook, waitFor} from "@testing-library/react";
import {afterEach, expect, it, vi} from "vitest";
import {createWorkspace} from "./workspace-state";
import {useDealWorkspace} from "./workspace-ui";

const seed = {caseId: "test-hook", issues: [], memoSections: [], scenarioValues: {growth: "20"}};
const refs = new Set<string>();
const contract = {fields: {growth: {kind: "NUMBER" as const, min: 0, max: 100}}};
const json = (value: unknown, status = 200) => new Response(JSON.stringify(value), {status});
afterEach(() => {delete window.__DESK_LOCAL_RUNTIME__; vi.unstubAllGlobals(); window.localStorage?.clear();});
it("locks initial editing, hydrates validated remote state, then saves with its version", async () => {
  window.__DESK_LOCAL_RUNTIME__ = true;
  let release!: (response: Response) => void;
  const pending = new Promise<Response>(resolve => {release = resolve;});
  const request = vi.fn().mockReturnValueOnce(pending).mockImplementation(async (_url, options) => json({version: 5, state: JSON.parse(options.body).state}));
  vi.stubGlobal("fetch", request);
  const {result} = renderHook(() => useDealWorkspace(seed, refs, contract));
  act(() => result.current.update({privateNote: "must not edit while loading"}));
  expect(result.current.state.privateNote).toBe("");
  expect(result.current.editingPaused).toBe(true);
  await act(async () => release(json({workspace: {version: 4, state: {...createWorkspace(seed), privateNote: "durable"}}})));
  await waitFor(() => expect(result.current.state.privateNote).toBe("durable"));
  expect(request).toHaveBeenCalledTimes(1);
  act(() => result.current.update({privateNote: "new note"}));
  await waitFor(() => expect(result.current.storageNotice).toBe("Saved to local workstation"));
  expect(JSON.parse(request.mock.calls[1][1].body).baseVersion).toBe(4);
});
it("surfaces conflicts with downloadable unsaved state and blocks further edits", async () => {
  window.__DESK_LOCAL_RUNTIME__ = true;
  const request = vi.fn().mockResolvedValueOnce(json({workspace: {version: 1, state: createWorkspace(seed)}})).mockResolvedValue(json({error: "workspace_conflict"}, 409));
  vi.stubGlobal("fetch", request);
  const {result} = renderHook(() => useDealWorkspace(seed, refs, contract));
  await waitFor(() => expect(result.current.editingPaused).toBe(false));
  act(() => result.current.update({privateNote: "unsaved conflict copy"}));
  await waitFor(() => expect(result.current.editingPaused).toBe(true));
  expect(result.current.storageNotice).toMatch(/Another window/);
  expect(result.current.recovery?.raw).toContain("unsaved conflict copy");
  const unload = new Event("beforeunload", {cancelable: true});
  window.dispatchEvent(unload);
  expect(unload.defaultPrevented).toBe(true);
  act(() => result.current.update({privateNote: "blocked"}));
  expect(result.current.state.privateNote).toBe("unsaved conflict copy");
  expect(request).toHaveBeenCalledTimes(2);
});
it("awaits a durable acceptance save before permitting source handoff", async () => {
  window.__DESK_LOCAL_RUNTIME__=true;
  let release!:(response:Response)=>void;
  const deferred=new Promise<Response>(resolve=>{release=resolve;});
  const request=vi.fn().mockResolvedValueOnce(json({workspace:{version:1,state:createWorkspace(seed)}})).mockReturnValueOnce(deferred);
  vi.stubGlobal("fetch",request);
  const {result}=renderHook(()=>useDealWorkspace(seed,refs,contract));
  await waitFor(()=>expect(result.current.editingPaused).toBe(false));
  let completed=false;
  let save!:Promise<void>;
  act(()=>{save=result.current.saveNow({privateNote:"acceptance checkpoint"}).then(()=>{completed=true;});});
  await waitFor(()=>expect(request).toHaveBeenCalledTimes(2));
  expect(completed).toBe(false);expect(result.current.editingPaused).toBe(true);
  await act(async()=>{release(json({version:2,state:JSON.parse(request.mock.calls[1][1].body).state}));await save;});
  expect(completed).toBe(true);expect(result.current.storageNotice).toBe("Saved to local workstation");
});
