import type {ModelProposal, SelectedEvidence} from "./model-workflow";
import {localProposalIsCurrent} from "./local-review";
import "./governance-review.css";

export type ProposalMemoUse = {sectionId: string; title: string; sourceProposalId?: string; scenarioSnapshotId?: string};
export function proposalHasSupportedReferences(proposal: ModelProposal, evidence: SelectedEvidence[], referenceLabels: Record<string, string>) {
  return proposal.evidenceRefs.length > 0 && proposal.evidenceRefs.every(id => evidence.some(item => item.id === id) || Boolean(referenceLabels[id]));
}
export function ProposalReviewDetail({proposal, evidence, referenceLabels, draft, onDraft, reviewer, onDecide, memoUses, reviewBasisId}: {
  proposal: ModelProposal; evidence: SelectedEvidence[]; referenceLabels: Record<string, string>; draft: string;
  onDraft: (body: string) => void; reviewer: string; onDecide: (decision: "ACCEPTED" | "REJECTED") => void; memoUses?: ProposalMemoUse[]; reviewBasisId?: string;
}) {
  const current = localProposalIsCurrent(proposal, evidence, reviewBasisId);
  const supported = proposalHasSupportedReferences(proposal, evidence, referenceLabels);
  const uses = memoUses?.filter(section => section.sourceProposalId === proposal.proposalId);
  const origin = proposal.origin === "LOCAL_MCP_REVIEW" ? "Local MCP proposal" : proposal.origin === "IN_PRODUCT_RUNTIME" ? "Hosted reviewer proposed" : proposal.origin === "LOCAL_MCP_LEDGER" ? "Local ledger proposal" : "Imported proposal · source unverified";
  const original = proposal.originalBody ?? proposal.body;
  const editable = proposal.state === "PROPOSED";
  const displayed = editable ? draft : proposal.body;
  const edited = original !== displayed;
  return <article className="governance-proposal" data-state={proposal.state}>
    <header><div><span className="eyebrow">{proposal.kind === "MEMO_DRAFT" ? "Memo language" : proposal.kind === "DILIGENCE_GAP" ? "Diligence request" : "Investment challenge"} · <span>{origin}</span></span><h3>{proposal.title}</h3></div><span className={`status status-${proposal.state.toLowerCase()}`}>{proposal.state.toLowerCase()}</span></header>
    {!current || !supported ? <div className="governance-blocker" role="status"><strong>{!supported ? "Supporting reference unavailable" : "Evidence or review basis changed"}</strong><p>{!supported ? "One or more citations cannot be matched to this deal. Resolve the missing source or request a new review before accepting." : "This proposal cannot be accepted; prepare a new review using current evidence. Any earlier acceptance remains historical judgment."}</p><button type="button" onClick={() => (document.getElementById("local-review-title") ?? document.getElementById("model-review-heading"))?.scrollIntoView({block: "start", behavior: "smooth"})}>Prepare another evidence review</button></div> : null}
    <div className="governance-proposal-body"><section aria-label="Proposal language"><div className="governance-language-heading"><h4>{editable ? "Review language" : "Reviewed language"}</h4><span>{edited ? "Human edits" : "Model text unchanged"}</span></div>{editable ? <label className="proposal-editor"><span>Review or edit proposal</span><textarea aria-label={`Edit ${proposal.title}`} maxLength={2000} value={draft} onChange={event => onDraft(event.target.value)} /></label> : <p className="governance-reviewed-text">{proposal.body}</p>}{edited ? <details className="proposal-diff" open><summary>Compare human-reviewed text to model draft</summary><section><span>Original model draft</span><p>{original}</p></section><section><span>Human-reviewed text</span><p>{displayed}</p></section></details> : null}</section>
    <section className="governance-citations" aria-label="Supporting evidence"><h4>Supporting evidence</h4><ol>{proposal.evidenceRefs.map(id => {
      const item = evidence.find(candidate => candidate.id === id);
      const sent = proposal.requestEvidence.find(candidate => candidate.id === id);
      const changed = item && sent && (item.displayValue !== sent.displayValue || item.summary !== sent.summary || item.title !== sent.title);
      return <li key={id}><strong>{item?.title ?? referenceLabels[id] ?? `Unrecognized reference: ${id}`}</strong>{item ? <><span>{item.displayValue}</span><p>{item.summary}</p></> : <p>{referenceLabels[id] ? "Registered deal reference. A selected-evidence snapshot is not available here." : "Cannot match this citation to the current deal."}</p>}{changed ? <div className="governance-snapshot"><span>Sent to reviewer: {sent.displayValue}</span><p>{sent.summary}</p></div> : null}</li>;
    })}</ol></section></div>
    <section className="governance-next-use" aria-label="Disposition and downstream use"><h4>Disposition and next use</h4>{proposal.state === "REJECTED" ? <p>Rejected language is retained for history and is not available for insertion as accepted memo language.</p> : proposal.kind === "MEMO_DRAFT" ? uses?.length ? <ul>{uses.map(section => <li key={section.sectionId}>{section.title} · {section.scenarioSnapshotId?.startsWith("stale:") ? "marked stale; reconcile in IC memo" : "linked memo section; check scenario alignment in IC memo"}</li>)}</ul> : <p>{memoUses ? "Not inserted in a memo section." : "Memo placement is not available in this view."} {proposal.state === "ACCEPTED" ? "A named editor can insert accepted language from the IC memo workspace." : "Acceptance makes this draft available for a named editor to insert in the IC memo."}</p> : <p>{proposal.kind === "DILIGENCE_GAP" ? `Suggested owner: ${proposal.proposedOwner ?? "unassigned"}. ` : ""}Acceptance records analyst judgment. Create or update a diligence issue separately to assign work; no issue is silently opened or resolved.</p>}<p className="governance-boundary">Financial inputs and calculated results are unchanged by this review.</p></section>
    <footer>{editable ? <><span>{reviewer.trim() ? `Reviewer: ${reviewer.trim()}` : "Enter a human reviewer above to record a disposition."}</span><div><button type="button" disabled={!reviewer.trim() || !current || !supported || !draft.trim()} onClick={() => onDecide("ACCEPTED")}>Accept proposal</button><button type="button" disabled={!reviewer.trim()} onClick={() => onDecide("REJECTED")}>Reject</button></div></> : <span>{proposal.humanEdited ? "Edited and " : ""}{proposal.state.toLowerCase()} by {proposal.humanActor}{proposal.reviewedAt ? ` · ${new Intl.DateTimeFormat("en-US", {month: "short", day: "numeric", year: "numeric"}).format(new Date(proposal.reviewedAt))}` : ""}</span>}</footer>
    <details className="technical-record"><summary>Review provenance and limitations</summary><p>{proposal.modelFamily ?? "Model identity not supplied"} · identity is self-reported, not authenticated</p><dl><dt>Request</dt><dd><code>{proposal.requestDigestSha256}</code></dd><dt>Response</dt><dd><code>{proposal.responseDigestSha256 ?? "No response digest supplied"}</code></dd></dl>{proposal.limitations ? <p>{proposal.limitations}</p> : null}<p>{proposal.origin === "LOCAL_MCP_REVIEW" ? "Current selected-evidence values are checked before acceptance." : "This origin does not provide the local snapshot freshness check. Inspect its citations before relying on it."}</p></details>
  </article>;
}
