import {useState, type ReactNode} from "react";
import "./review-system.css";
export interface ReviewColumn<T> {id:string; label:string; render:(row:T)=>ReactNode; sortValue?:(row:T)=>string|number; numeric?:boolean}
export function ReviewTable<T>({label,rows,columns,rowKey,selectedId,emptyMessage="No records match this view.",className=""}: {label:string; rows:T[]; columns:ReviewColumn<T>[]; rowKey:(row:T)=>string; selectedId?:string; emptyMessage?:string; className?:string}) {
  const [sort,setSort]=useState<{id:string; direction:"ascending"|"descending"}|null>(null);
  const column=columns.find(item=>item.id===sort?.id);
  const ordered=column?.sortValue ? [...rows].sort((a,b)=>{const left=column.sortValue!(a),right=column.sortValue!(b); const result=typeof left==="number"&&typeof right==="number" ? left-right : String(left).localeCompare(String(right),undefined,{numeric:true}); return (sort?.direction==="descending"?-1:1)*result;}) : rows;
  return <div className={`review-table-scroll ${className}`}><table className="review-table" aria-label={label}><thead><tr>{columns.map(item=><th key={item.id} scope="col" className={item.numeric?"numeric":""} aria-sort={item.sortValue ? sort?.id===item.id?sort.direction:"none":undefined}>{item.sortValue?<button type="button" aria-label={`Sort by ${item.label}`} onClick={()=>setSort(sort?.id===item.id&&sort.direction==="descending"?null:{id:item.id,direction:sort?.id===item.id?"descending":"ascending"})}>{item.label}<span aria-hidden="true">{sort?.id===item.id?(sort.direction==="ascending"?" ↑":" ↓"):" ↕"}</span></button>:item.label}</th>)}</tr></thead><tbody>{ordered.length?ordered.map(row=><tr key={rowKey(row)} data-selected={rowKey(row)===selectedId||undefined}>{columns.map((item,index)=>index===0?<th key={item.id} scope="row" className={item.numeric?"numeric":""}>{item.render(row)}</th>:<td key={item.id} className={item.numeric?"numeric":""}>{item.render(row)}</td>)}</tr>):<tr><td colSpan={columns.length} className="review-table-empty">{emptyMessage}</td></tr>}</tbody></table></div>;
}
