import { describe, it, expect } from 'vitest';
import { zipSync, strToU8 } from 'fflate';
import { readWorkbook } from './workbook-diff';
import { suggestMappings, mappedFinancials } from './workbook-intake';
function wb(cells: string) { return zipSync(Object.fromEntries(Object.entries({ 'xl/workbook.xml': '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Actuals" sheetId="1" r:id="r1"/></sheets></workbook>', 'xl/_rels/workbook.xml.rels': '<Relationships><Relationship Id="r1" Target="worksheets/sheet1.xml"/></Relationships>', 'xl/worksheets/sheet1.xml': `<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row>${cells}</row></sheetData></worksheet>` }).map(([k, v]) => [k, strToU8(v)]))).buffer as ArrayBuffer; }
const t = (a: string, v: string) => `<c r="${a}" t="inlineStr"><is><t>${v}</t></is></c>`, n = (a: string, v: number) => `<c r="${a}"><v>${v}</v></c>`;
describe('workbook-first mapping', () => {
    it('detects horizontal periods and optional EBITDA', () => { const b = wb(t('B1', '2024 actual') + t('C1', '2025 actual') + t('A2', 'Revenue') + n('B2', 100) + n('C2', 120) + t('A3', 'EBITDA') + n('B3', 10) + n('C3', 20)); const m = suggestMappings(readWorkbook(b).get('Actuals')!); expect(m).toEqual([{ period: '2024 actual', revenue: 'B2', earnings: 'B3' }, { period: '2025 actual', revenue: 'C2', earnings: 'C3' }]); expect(mappedFinancials(b, 'Actuals', m, 1000)[1].revenue.value).toBe(120000); });
    it('detects vertical periods with missing earnings left unavailable', () => { const b = wb(t('B1', 'Revenue') + t('A2', 'Q1 actual') + t('A3', 'Q2 actual') + n('B2', 100) + n('B3', 120)); const m = suggestMappings(readWorkbook(b).get('Actuals')!); expect(m[1]).toEqual({ period: 'Q2 actual', revenue: 'B3', earnings: '' }); expect(mappedFinancials(b, 'Actuals', m, 1)[0].earnings).toBeNull(); });
    it('supports manual cells for unusual layouts without guessing a definition', () => { const b = wb(t('C7', 'Bookings, not revenue') + n('D9', 200)); expect(suggestMappings(readWorkbook(b).get('Actuals')!)).toEqual([]); expect(mappedFinancials(b, 'Actuals', [{ period: '2025 forecast', revenue: 'D9', earnings: '' }], 1)[0].revenue.value).toBe(200); });
    it('retains formulas without evaluating them', () => { const b = wb('<c r="B2"><f>1+1</f><v>17</v></c>'); expect(mappedFinancials(b, 'Actuals', [{ period: 'FY25 actual', revenue: 'B2', earnings: '' }], 1)[0].revenue).toEqual({ value: 17, address: 'B2', formula: '1+1' }); });
    it('rejects absent values, repeated cells, duplicate periods and unconfirmed units', () => { const b = wb(n('B2', 100)); const m = { period: '2025', revenue: 'B2', earnings: '' }; expect(() => mappedFinancials(b, 'Actuals', [{ ...m, revenue: 'B9' }], 1)).toThrow(); expect(() => mappedFinancials(b, 'Actuals', [{ ...m, earnings: 'B2' }], 1)).toThrow(/more than once/); expect(() => mappedFinancials(b, 'Actuals', [m, m], 1)).toThrow(/unique/); expect(() => mappedFinancials(b, 'Actuals', [m], 100)).toThrow(/units/); });
});
